w3c/browser-specs

.github/workflows/lint.yml
README.md
index.js
lint.js
package-lock.json
package.json
schema.json
specs.json
test/lint.js

In most cases, a URL should be all we need in that list. Getting rid of the wrapping `{ "url": ... }` struct in these cases allows to keep the list more human readable.
This update allows entries to be just a string. Linting code updated to prefer the string format when there is only a URL (which is going to be the case as long as we don't create additional properties). Specifications remain sorted by alphabetic order of their URL.
The `index.js` file continues to export an array of objects with a `url` property to ease ingestion by external tools.
See discussion in:
https://github.com/w3c/browser-specs/pull/2#pullrequestreview-345692753
(Note that if we actually discover later on that a URL is **not** enough in most cases, we may want to undo this change...)

Allow specs to be represented by a simple string

---

lint.js
test/lint.js

It is relatively easy to end up with duplicate URLs if they get added in bulk.
The linter now only keeps the first one.

Detect and drop duplicate URLs when linting

---

index.js
lint.js
schema.json
src/compute-shortname.js
test/compute-shortname.js
test/lint.js

Most specification URLs follow a few common patterns from which it is easy to derive a shortname (e.g. "webauthn-2" from "https://www.w3.org/TR/webauthn-2/"). In turn, this shortname can be used to derive a level ("2" for "webauthn-2") and a family name that is common across levels of the spec ("webauthn" here).
The "compute-shortname.js" module does just that. It handles main types of URLs and returns an object with "shortname", "familyname", and a "level" property when that makes sense.
An exception is thrown when the shortname cannot be computed. When that happens, the corresponding entry in "specs.json" should be updated to make the shortname (and/or family name and/or level) explicit. For instance, the entry for CSS Media Queries Level 3 should typically read:
```json
{
"url": …
```

Add logic to compute shortname, family name and level

---

index-schema.json
index.js
lint.js
specs-schema.json
specs.json
src/compute-prevnext.js
test/compute-prevnext.js
test/index.js
test/lint.js

To make sense of the contents of a given spec, it is necessary to track whether it is a "delta" spec that may not contain the entire contents of the previous level or a "full" spec. This update allows specs to be defined as delta specs.
Whether the spec is a delta spec cannot be determined automatically. Delta specs need to be flagged with a "delta" flag in specs.json through a `delta` property as in:
```json
{
"url": "https://www.w3.org/TR/mydelta-2/",
"delta": true
}
```
To keep the list of URLs in specs.json readable, the flag can also be specified directly within the string that describes the spec, after the URL:
```
"https://www.w3.org/TR/mydelta-2/ delta"
```
This notation is syntactic sugar for the previous notation and can only be used when a string is used to describe the …

Allow delta flag and add previous/next links

---

index-schema.json
index.js
lint.js
specs-schema.json
src/compute-currentlevel.js
test/compute-currentlevel.js
test/lint.js

See #9.
Groups may work on multiple levels of a given spec at once, and may want to redirect readers to one of these levels by default.
With this update, the code exposes a new `currentLevel` property for each spec in the list that points at the name of the specification with the same shortname that should be viewed as the current one.
By default, the `currentLevel` property points at the latest level that is not a delta spec. This rule may be overwritten by flagging the entry that should be seen as the current level in specs.json. This can be done through a `forceCurrent` boolean property:
```json
{
"url": "https://www.w3.org/TR/spec-1",
"forceCurrent": true
}
```
... or inline next to the URL with a `current` keyword:
```json
"https://www.w3.org/TR/spec-1 current"
```
The linter …

Add currentLevel property

---

index.js
index.json
lint.js
schema/definitions.json
schema/index.json
schema/specs.json
src/build-index.js
src/compute-currentlevel.js
src/compute-prevnext.js
src/compute-shortname.js
src/fetch-info.js
test/compute-currentlevel.js
test/compute-prevnext.js
test/compute-shortname.js
test/fetch-info-w3c.js
test/fetch-info.js
test/index.js
test/lint.js

See #25.
Following exchanges with W3C API folks, this update aligns terms used in browser-specs with existing or upcoming terms in the W3C API, where it makes sense.
In practice, this update brings the following changes:
- `shortname` becomes `series.shortname`
- `name` becomes `shortname`
- `level` becomes `seriesVersion` and is now a string
- `levelComposition` becomes `seriesComposition`
- `currentLevel` becomes `series.currentSpecification`
- `previousLevel` becomes `previousInSeries`
- `nextLevel` becomes `nextInSeries`
- `edUrl` becomes `nightly.url` and is set for all specs
- `trUrl` becomes `release.url` and is only set for TR specs
Many lines of code changed, but it's all renaming...

Align property names with W3C API

---

.release-it.json
package-lock.json
package.json

See #13.
Idea is to use [release-it](https://github.com/release-it/release-it#release-it-) to manage releases. With the update, a new release should be doable through the following command-line:
```
npm run release
```
Command must be run from the `master` branch. A `GITHUB_TOKEN` env variable needs to be set to a GitHub Personal Access Token with `repo` rights.
The release-it library will take care of enforcing that the local folder looks good (no pending changes) and that tests pass before releasing the new version. It will create a new commit "vX.Y.Z", a new tag, a new GitHub Release with a changelog, and publish the package to npm.
The GitHub release should give access to archives of the source code at the time of the release. The npm package will mainly contain the `index.json` file, …

Add code to manage releases

---

specs.json

The spec used to be called `video.requestAnimationFrame()`. It is now called `HTMLVideoElement.requestVideoFrameCallback()` and its URL has changed.

Update URL of requestVideoFrameCallback spec

---

LICENSE.md

This flags the index.json file as being published under the terms of the CC0 license. See discussion in #28.

Add CC0 license for the actual list of specs

---

package.json

The browser-specs "package" only contains the index.json file, so CC0 applies to it. The LICENSE.md file is clear that the rest of the code is licensed under the terms of the MIT license.

Add CC0 license to package.json

---

.release-it.json

See #44.
The changelog was updated too late in the release process and the update wasn't included in the commit as a result. Using `after:bump` as specified in the documentation should fix the issue:
https://github.com/release-it/release-it/blob/master/docs/changelog.md#auto-changelog

Release process: update changelog before commit

---

index.json
specs.json

The list contains the nightly version of the spec, which makes sense but also generates a `ServiceWorker` shortname that should rather be `service-worker` (shortname used in /TR/).
This update forces the shortname to `service-worker`.

Force Service Worker spec shortname

---

specs.json

Previous update (see #48) forced the shortname of the Service Workers spec but missed the
fact that the actual shortname uses a plural form: `service-workers`.

Use plural for Service Workers shortname

---

specs.json

Recent release of the W3C API includes adjustments to default shortnames for some of the specs. A couple of updates were needed for the CSS Images Module Level 3 and Trace Context.
The W3C API returns a 301 redirect when a non default shortname is used, which the code in `fetch-info.js` currently does not support (which explains why update is crashing for now). That should probably be fixed, but it seems a good thing in any case to align default shortnames with those of the W3C API.

Adjust a couple of TR URLs to match W3C API shortnames

---

specs.json

https://wicg.github.io/budget-api/ "is not being actively maintained"
The implementation was removed from Chromium:
https://groups.google.com/a/chromium.org/d/msg/blink-dev/18r3whCBv0I/b8qrtFTsDAAJ

Remove Web Budget API

---

specs.json

The repo was renamed, see https://github.com/WICG/admin/issues/112.

Update CSS Parser API URL

---

specs.json

Spec migrated to WebApps WG:
https://github.com/w3c/web-share-target/issues/87

Update URL of Web Share Target spec

---

package-lock.json
package.json
src/data/ignore.json
src/data/monitor-repos.json
src/find-specs.js

per #50
Looks into the report from validate-repo for repos associated with browser-spec producing WGs and well-known browser-spec producing CGs (both lists curated manually) and match that list of repos with URLs known in browser-spec

Add script to find list of specs potentially in scope

---

specs.json

The spec has been adopted by the WebRTC WG and has early experimental implementations in Chromium

Add WebRTC Insertable Streams

---

.github/candidate-specs.md
.github/workflows/report-new-specs.yml
package-lock.json
package.json
src/find-specs.js

per #71
no idea if this will actually work, and not really sure how to test it beyond deploying it?

Report specs found as candidates as github issue

---

specs.json
src/data/ignore.json

Implementation plans aren't all that clear, but probably not substantively different from e.g. SVG Animations which is already in the list

Move SVG Streaming to ignore list 

---

specs.json

Spec already covered through a /TR/ URL.
See discussion in https://github.com/w3c/browser-specs/pull/90#issuecomment-644755268

Drop MediaStream Depth ED URL

---

specs.json

Has an implementation in Chrome behind a flag https://www.chromestatus.com/features/5695114963845120
this should probably be handled similarly to our approach to #86

Add Media Feeds spec

---

CONTRIBUTING.md
schema/specs.json
specs.json
src/build-index.js

Authors may now specify the nightly URL in `specs.json` through the `nightly` object.
The update also changes the Service Workers entry to use the /TR/ URL (and overrides the nightly URL)
Fixes #94.

Allow nightly URL in specs.json, adjust Service Workers entry

---

README.md
index.json
schema/definitions.json
schema/index.json
schema/specs.json
src/build-index.js
src/compute-repository.js
src/fetch-info.js
test/compute-repository.js
test/index.js

See #19. The repository is either retrieved from Specref or computed from the nightly URL.

Expose spec repository in nightly.repository

---

src/data/ignore.json

It now redirects to WHATWG HTML and is thus a duplicate

Ignore /TR/html

---

.github/workflows/monitor-specs.yml
src/monitor-specs.js

The script checks the last-modified headers on the specs and highlights those that have changed since last review; it submits as a pull request (via a github action) the list of repos/specs to be monitored updated with a last review date of the day it is running on
See #113 for an example of what it produces.

Add script to assist in updating monitored specs

---

CONTRIBUTING.md
README.md
index.json
schema/index.json
schema/specs.json
specs.json
src/build-index.js
src/compute-shorttitle.js
test/compute-shorttitle.js

See #12. The shortTitle property gets computed from the full title by dropping common terms and applying a few additional regular expressions. The shortTitle property may be specified in specs.json.
There should be ~25 specs for which we'll likely have to maintain the short title manually in specs.json. I haven't included them in the pull request so that we can first check that the automatic generation does not produce weird results.

Add shortTitle property

---

specs.json

Shortname was fixed in W3C systems, and CSS2 is now an alias that redirects to CSS21.

Use CSS21 instead of CSS2 address

---

specs.json

This update adds manual short titles to specifications when the automatic generation does not give a good enough result, and when there is a known short title in Shepherd. See:
https://github.com/w3c/browser-specs/issues/12#issuecomment-646332857
This somewhat destroys my until-then-good-looking array of strings with plenty of objects :(

Add short titles to specs.json

---

README.md
index.json
schema/definitions.json
src/build-index.js
src/determine-filename.js
test/determine-filename.js
test/index.js

This update adds a `filename` property to `release` and `nightly` to report the actual filename of the index page, with a view to allowing external code to identify all links to self.
The code extracts the filename from the URL if it already appears there. For instance, it extracts the filename `identity.html` from
`https://w3c.github.io/webrtc-identity/identity.html`.
If the filename is not in the URL, the code uses a trial and error approach: it appends `Overview.html` (most common filename) to the URL and fetches the resulting URL. If that fails, it tries with `index.html` (second most common filename). If that also fails, it tries with `cover.html` (which is essentially only used for the main CSS spec). So far, this is enough to cover all existing specs but note the code also looks at …

Expose filename of the index page

---

src/monitor-specs.js

the CSS draft servers uses a proprietary last-revised header which seems to give more useful information on the actual last modification of a spec, so we use it when it is available

Handle Last-Revised header in spec monitor

---

src/determine-filename.js
test/determine-filename.js
test/extract-pages.js

The Editor's Draft of CSS2 was converted to Bikeshed recently:
https://github.com/w3c/csswg-drafts/pull/5196
This means that the spec becomes single page for now (at least until Bikeshed
supports multipage specs).
This update drops `cover.html` as "common" filename, since it was only used
there, and adjusts tests to only expect multiple page from the published
CSS 2.1 version.
Note the published version of CSS 2.2 still has multiple pages, so the spec
still needs to retain the `multipage` flag in `specs.json`.

CSS2 ED switched to Bikeshed, no longer multipage

---

package.json
src/build-index.js

CSS drafts server does not seem to like it when it receives too many requests in a row (see #130). This makes the `filename` info switch back and forth between `null` and its correct value.
To avoid this, this update re-uses the previous information as a fallback. The update also makes the code sleep 50ms between requests (this means the generation takes about 20s more than it used to).
Also, note that the generation logic had to be changed slightly to avoid having a `> index.json` command in `package.json`, since that was resetting the `index.json` file right away (and in particular before the code could load it).

Use previous filename when it cannot be determined

---

specs.json

Spec re-published with a new shortname `permissions-policy` instead of `feature-policy`.

Update URL of Permissions Policy spec

---

src/data/ignore.json
src/data/monitor.json

While the HTML Sanitizer API spec is already advanced (and under active development), there does not seem to be clear implementation plans yet. Adding the spec to monitor list as a result.
Fixes #132

Ignore WebXR weekly repo and monitor Sanitizer API repo

---

src/data/monitor.json

close #136 
also, amend #134 by removing WICG/purification (which has been renamed as WICG/sanitizer-api)

Mark WebID as to be monitored

---

.github/workflows/monitor-specs.yml
.github/workflows/report-new-specs.yml
src/find-specs.js

So far, find-specs would only use cg-report as a hint to look if the repo has a home page or not, and if not, would simply check if a generated page exists.
With this change, cg-report causes repos to be automatically flagged as relevant if they have a cg-report type. This identifies a bunch of new repos (and so closes #150). That being said, since these are repos which don't have github generated pages, it's not clear whether they're really ready for inclusion in browser-specs.

Use cg-report as a stronger hint of relevance

---

specs.json

Repository dropped the `-` in its name.

Update URL of WebTransport spec

---

specs.json

Perhaps a bit early still, but the spec was adopted by the WebRTC Working Group.
Fixes #171

Add Media Capture Automation

---

specs.json

Level 3 is marked as current work in [Shepherd](https://drafts.csswg.org/) and https://www.w3.org/TR/css-box/ redirects to level 3.
Triggered by https://github.com/tidoust/reffy/issues/417#issuecomment-707701186

Flag CSS Box 3 as current specification

---

specs.json

Several CSS specifications, being developed by the CSS WG, supersede a previous level published as a W3C Recommendation, meaning that the series shortname no longer targets the Recommendation, but rather targets the new level. That suggests that the previous level no longer needs to be tracked in browser-specs (at least, that is the rule we follow for IDL specs).
This update removes the following CSS Recommendations from the index as a result:
- [CSS Color 3](https://www.w3.org/TR/css-color-3/)
- [CSS Containment 1](https://www.w3.org/TR/css-contain-1/)
- [CSS Fonts 3](https://www.w3.org/TR/css-fonts-3/)
- [CSS Basic UI 3](https://www.w3.org/TR/css-ui-3/)
- [CSS Writing Modes 3](https://www.w3.org/TR/css-writing-modes-3/)
- [CSS Mediaqueries 3](https://www.w3.org/TR/css3-mediaqueries/)
- …

Drop superseded CSS Recommendations

---

specs.json
src/data/ignore.json

- Drop CSS Grid Level 1 as /TR/css-grid/ now redirects to Level 2
- Update CSS Grid Level 2, no longer a delta spec
- Add CSS Grid Level 3, delta spec
- Update URL of CSS Highlight API Level 1
- Update URL of WebXR Hand Input
- Add EPUB3 repo to ignore list, not targeted at browsers
Fixes #180

Update CSS Grid, CSS Highlight, WebXR Hand Input

---

specs.json

https://drafts.css-houdini.org/worklets/ now redirects to HTML,
into which it's been integrated.

Drop Worklets spec

---

src/data/ignore.json

The Worklets specification is now part of the HTML specification, and was dropped from browser-specs last week.
The newly created WICG repository on reducing memory copies is intended for discussion only.
Fixes #183.

Ignore Worklets spec and discussion repo on memory copies

---

specs.json
src/build-index.js
src/compute-currentlevel.js
src/fetch-info.js
test/fetch-info-w3c.js

Fixes #176.
The current specification in a series of specifications was the last level that was not a delta spec, unless otherwise specified in specs.json.
This update extends the definition as follows: for W3C specifications, the current specification becomes the one returned by the W3C API, unless otherwise specified in specs.json, and provided that the current specification returned by the W3C API is in the list.
In turn, this allows us to drop the manual "current" entries in specs.json. They are no longer needed, the W3C API returns the right info for them.
This will trigger one change in the resulting index: the current specification for Compositing and Blending will become Level 1. It used to be Level 2, but Level 2 has not been published as a /TR/ draft yet, so it makes sense to me …

Get current specification from W3C API

---

.github/candidate-specs.md

Link is currently broken, see for example https://github.com/w3c/browser-specs/issues/188

Fix relative link to find-specs script

---

.github/incorrect-base-url.md
.github/workflows/check-base-url.yml
src/check-base-url.js

The base URL of a specification should either match its release URL if there is one or its nightly URL otherwise.
This update adds a `check-base-url` script and a weekly GitHub action, run on Mondays at 00:30 (to avoid collision with the monitor action), to make sure that this is actually the case. The action creates an issue when there are specifications to check.
Cancels and replaces #72.

Add periodic check on base URL

---

.github/workflows/monitor-specs.yml
.github/workflows/report-new-specs.yml

v2 uses `set-env` commands which have been deprecated from GitHub:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
The action fails as a reusult (even though it still manages to create a PR somehow).

Bump version of create-pull-request GitHub action

---

index.json
specs.json
src/compute-repository.js
src/compute-shortname.js
src/data/ignore.json
src/fetch-info.js
src/find-specs.js
test/compute-repository.js
test/compute-shortname.js

do not merge for now - reffy is not ready to work with github markdown pages as "specs".

Add ECMA 262 and TC39 Stage 3 proposals to the list of specs 

---

src/find-specs.js

tc39.es rather than tc39.github.io

Use correct URL for prefix when looking for new ECMA specs

---

package.json

The published package only contains the index.json file and should not have any direct dependencies.

Move dependencies to developer dependencies

---

index.js

Not sure how they ended up in there, but these lines are useless.

Drop useless imports in index.js script

---

specs.json

`css3-conditional` now redirects to `css-conditional-3`

Adopt new TR shortname for CSS Conditional 3

---

specs.json

Automatically generated short title is:
"Web Authentication: An API for accessing Public Key Credentials: 2"
This update shortens is to "Web Authentication". No level indication since we
don't have any other levels in the list.
Close #197.

Define short title for webauthn explicitly

---

.github/workflows/build.yml
CONTRIBUTING.md
README.md
index.json
package-lock.json
package.json
schema/definitions.json
specs.json
src/build-index.js
src/compute-repository.js
test/compute-repository.js
test/index.js

This update makes the build process compute the relative path to the source of the nightly version of each spec at the HEAD of the default branch of the spec repository. That information gets exposed in the `nightly.sourcePath` property.
The code retrieves and parses the tree of the repository from the GitHub API, looking for common patterns (such as `index.bs`). The code follows the same logic as in the Web IDL updater in:
https://github.com/saschanaz/webidl-updater/blob/main/src/find-source-path.js
As opposed to the approach taken in the auto updater, the code here does not attempt to differentiate between types of specs (because that does not seem needed) and does not try to deal with exceptions-to-the-rule which rather need to be handled by specifying `nightly.sourcePath` in …

Expose path to source of nightly spec in sourcePath

---

schema/data.json
src/data/monitor.json
test/data.js

Tests also make sure that there cannot be an entry that is both in the ignore list and in the monitor list.
Note the check on repository names may be a bit too constrained as one can probably use other characters in repo names, but then all repos pass this for now.
Close #214.

Add tests to validate JSON files in data folder

---

specs.json

The `ecma-402` shortname is based on that used in Specref.
Short title may be too short, perhaps?

Add ECMAscript Internationalization API spec

---

src/compute-shortname.js
test/compute-shortname.js

Shortnames of WebGL extensions and ECMA specs sometimes end with digits that were incorrectly interpreted as level numbers. This update excludes these specs from the level extraction logic. In turn, this makes the code generate the right `seriesVersion` property for these specs (none in practice) and the right `series.shortname`.
Close #221.

Fix version extraction for WebGL extensions and ECMA specs

---

.gitignore
CONTRIBUTING.md
README.md
index.json
schema/definitions.json
schema/index.json
schema/specs.json
specs.json
src/build-index.js
src/determine-testpath.js

This update exposes a new `tests` property that details, when that is possible:
1. the URL of the repository that contains the test suite for the spec
2. the actual paths in that repository that contain the test suite
3. if needed, the sub-paths to exclude from the list of paths because they actually contain tests for another specification
@foolip That information should allow you to drop all `testrepo` and `testpath` entries in [day-to-day/specs-fixes.json](https://github.com/foolip/day-to-day/blob/main/specs-fixes.json) and associated logic. FWIW, the list of folders for HTML in that file does not seem fully correct anymore (`shadow-dom` should rather be associated with DOM, `2dcontext`, `innerText` and `offscreen-canvas` no longer exist, and `x-frame-options` should also be in the …

Expose test repository and paths for each spec

---

schema/data.json
src/data/ignore.json
src/find-specs.js

The tool that looks for potential new specs did not always check candidate repos against the list of repos in `ignore.json` and `monitor.json`. This update forces the code to look at these lists when it considers whether a candidate is in scope.
Note explicit checks on the initial list of repos are no longer stricto senso necessary and have been dropped.
Done to address #229, which should not have contained EPUB entries because the underlying repo is in the ignore list.

Always check repo against ignore/monitor lists

---

specs.json
src/data/monitor.json

CSS Cascading Level 5 was published as FPWD last week, so URL needs to be updated.
@deniak, I thought the CSS WG wanted links to the editor's draft to link to the right version, but published versions of levels 4 and 5 link to the unversioned https://drafts.csswg.org/css-cascade/. I would rather have expected:
- https://www.w3.org/TR/css-cascade-4/ to target https://drafts.csswg.org/css-cascade-4/
- https://www.w3.org/TR/css-cascade-5/ to target https://drafts.csswg.org/css-cascade-5/
Also, the versionless https://www.w3.org/TR/css-cascade/ targets Level 5. I would have expected it to continue to target Level 4, which is still a Working Draft. That would be consistent with https://drafts.csswg.org/css-cascade/. Or is that intended?
(Beware if you make updates to the W3C database ;))
This …

Update URL of CSS Cascading Level 5 / Monitor Web Audio API v2 repo

---

specs.json
src/data/monitor.json

This is implemented in Safari, and was also in Edge 18.

Add DataCue API

---

src/data/monitor.json

Both specs are marked as "not ready for implementations".
Close #243

Add CSS Conditional Values and CSS Fonts 5 to monitor list

---

specs.json
src/data/monitor.json

Per https://github.com/w3c/svgwg/issues/824#issuecomment-790920790 they're incomplete and unmaintained, and they end up creating conflicting IDL views with the main SVG2 specs.
They're included both with their editors and TR urls since they can't be tracked at the repo level (multi-spec repo).
close #247

Move SVG Paths and Markers to monitor list

---

src/data/ignore.json

Specs are not - or at least not yet - targeted at browsers.
Closes #254.

Ignore specs from MiniApps Working Group

---

specs.json

URL was fixed in the spec:
https://github.com/w3c/webappsec-fetch-metadata/pull/69

Drop nightly URL override for Fetch Metadata

---

schema/definitions.json
specs.json
test/fetch-info-w3c.js

This adds three requested specs that sit at the boundary of spec selection
criteria for browser-specs:
1. DNT, requested in #281
2. SVG 1.1, requested in #273
3. Web App Manifest - App info, requested in #283
The SVG 1.1 entry uses SVG 2 as nightly URL for lack of a better alternative.
JSON schema has to be slightly adjusted to account for the "-" in
"tracking-dnt.html". Also, a test started to fail because "hr-time-3" is now
the default level for HR Time.

Add DNT, SVG 1.1, and Manifest App info specs

---

specs.json
src/data/monitor.json

Follows from discussions in:
https://github.com/w3c/browser-specs/issues/279#issuecomment-831634786
The specs are flagged with a "not ready for implementation" banner, but already documented in BCD in practice, and implemented in at least one browser.

Add Web Animations 2 and CSS Fonts 5

---

.github/workflows/build.yml
.github/workflows/check-base-url.yml
.github/workflows/lint.yml
.github/workflows/monitor-specs.yml
.github/workflows/report-new-specs.yml
README.md
index.json
schema/definitions.json
src/build-index.js
src/compute-series-urls.js
test/compute-series-urls.js
test/index.js

This adds a `releaseUrl` and `nightlyUrl` properties to `series` objects that target the unversioned URLs.
The properties are set when possible. In many cases, typically when the spec is a non-leveled spec, they are set to the same URLs as the `release.url` and `nightly.url` properties.
Generation code remains fairly generic. This seems to work well.
Fixes #282.

Add "releaseUrl" and "nightlyUrl" to "series" objects

---

specs.json

Spec published as First Public Working Draft.
Close #293

Switch to /TR URL for WebTransport

---

specs.json

There’s now a multipage version of the ECMAScript spec, at https://tc39.es/ecma262/multipage/. This change switches to the multipage version, rather than the single-page version. cc @Elchi3

Switch ecma262 spec to multipage version

---

specs.json

Adds Accessible Object.hasOwnProperty:
https://tc39.es/proposal-accessible-object-hasownproperty/
Adds Resizable ArrayBuffer and growable SharedArrayBuffer:
https://tc39.es/proposal-resizablearraybuffer/
Fixes #303.

Add TC39 proposals hasOwn and resizable ArrayBuffer

---

src/find-specs.js

Per https://github.com/w3c/browser-specs/issues/308#issuecomment-856084703

Recognize tc39-transfer as equivalent to tc39 when finding specs

---

specs.json
src/compute-repository.js
src/compute-series-urls.js
test/compute-repository.js
test/compute-series-urls.js

Fixes #312.
This update required a couple of additional code updates:
- in the code that computes the URL of the repository to use the `repository` info if it is specified in `specs.json`.
- in the code that computes the `releaseUrl` and `nightlyUrl` to use the current specification in a series as basis for the info (the code happily produced a different nightly URL for SVG 1.1 and SVG 2)

Use /TR URL for SVG 1.1 spec

---

.github/workflows/build.yml

Build workflow used an old version of github-push-action, which used `master`as default branch name. The latest version uses the actual default branch.

Use latest version of github-push-action

---

specs.json

No longer user an exception per https://github.com/w3c/paint-timing/pull/91
close https://github.com/w3c/browser-specs/issues/330

Reflect new source file for painttiming

---

specs.json

Does not match the browser-spec requirements
Bis of https://github.com/w3c/browser-specs/pull/195 which one way or another didn't work?

Remove Trace Context

---

specs.json

The RFC talks of a Network Working Group, the same as the one quoted on https://datatracker.ietf.org/doc/html/rfc3987 which has a WG link to https://datatracker.ietf.org/group/app/
close #343

Document WG manually for RFC2397

---

src/data/ignore.json
src/data/monitor.json

I don't really know what to do with this spec, raised in #350. I propose to add it to the monitor list for now. Spec is under development within the MathML WG but it is mostly a copy of MathML 3 for now, is not yet based on MathML Core and, as opposed to MathML Core that specifically targets browsers, is likely going to define features that won't be implemented by browsers.

Monitor MathML 4 spec

---

specs.json
src/data/ignore.json

The IDL that the spec defined has now been fully integrated in CSSOM

Drop Constructable Stylesheet Objects

---

specs.json

This update adds CSS Cascade 6 and drops CSS Scoping 2 as a result (the latter spec now redirects to the former).
It also adds the Scripting Policy and Close Watcher API. The two specs are still at early stages and in a grey zone vis-à-vis our spec selection criteria but development is active and proposals are backed by implementers, see:
https://github.com/WICG/proposals/issues/18
https://github.com/WICG/proposals/issues/36
Fixes #375

Add CSS Cascade 6, Scripting Policy, Close Watcher

---

specs.json

The code cannot find the source path by itself.

Add source path for Scripting Policy spec

---

specs.json
src/data/monitor.json
src/fetch-info.js
test/fetch-info.js

This update also improves the title extraction logic for TC39 specs, because one of the Intl proposals actually puts the title in the third `<h1>` and not the second one.
Close #386.

Add TC39 Intl proposals, Compute Pressure, Conditional Focus

---

specs.json
src/data/monitor.json

The Intl.NumberFormat proposal may be at stage 3 but it only exists as a README for now (and README claims it is at stage 2...). Our code cannot set the `sourcePath` as a result and it seems premature to add the spec as a result.
Also, the `tc39-` prefix was missing from the Intl.DisplayNames shortname and the series shortname didn't look too good. Code could probably be fixed to support `-vXX` URL suffixes, but then there is only one occurrence of such a URL for the time being, so handling it directly in specs.json.
Close #388.

Monitor Intl.NumberFormat, fix shortnames of Intl.DisplayNames

---

specs.json
src/fetch-groups.js
test/fetch-groups.js
test/index.js

See #390. The specs don't belong to browser-specs in theory and we may want to separate or flag these documents somehow later on. In the meantime, they define useful terms that other specs may want to reference.
This required a few fixes to the `fetch-groups.js` utility which crashed on these entries (even though their groups are explicitly set in `specs.json`). Also, the Patent Policy document is not developed in any GitHub repository for now, so the tests that looked for `repository` on all non IETF specs needed to be adjusted as well.

Add W3C Process and Patent Policy document, adjust tools and tests

---

specs.json

The "media-source" shortname is now an alias to "media-source-2".

Update MSE URL following FPWD publication

---

specs.json

This is to allow the specification to be referenced in the MDN browser compatibility data: https://github.com/mdn/browser-compat-data/pull/12446
It adds
- RFC4120: The Kerberos Network Authentication Service (V5)
- rfc7616: HTTP Digest Access Authentication
- RFC7617: The 'Basic' HTTP Authentication Scheme

Add RFC4120, 7616, 7617: Various Authentication protocols

---

specs.json
src/data/ignore.json

Spec got folded into HTML, see:
https://github.com/w3c/page-visibility/issues/74

Drop Page Visibility

---

specs.json
src/data/ignore.json
src/data/monitor.json

This updates the URLs of a few specs that started their journey on TR:
- CSS Fonts Level 5
- Incremental Font Transfer
- MathML Core
- WebXR AR Ligtning estimation
This also adds the navigation speculation specs to the monitoring list for now, ignoring the core spec that just targets these two specs.
Fixes #436

Update URLs of ED published to TR, monitor nav-speculation

---

specs.json
src/data/monitor.json

- CSS Values 5 is a new delta spec from the CSS WG
- Array Grouping is a stage 3 TC39 proposal
- Model Element is for WebXR, but a placeholder for now
- the Chinese Layout Gap Analysis is on the Note track but incorrectly flagged as on the Rec track for now.
Close #453.

Add CSS Values 5, ES Array grouping, monitor Model Element and clreq

---

specs.json
test/specs.js

Delta spec was published as First Public Working Draft today.
(via #453)

Add CSS Conditional Level 5

---

specs.json

This update adds 2 new FPWD:
- Edit Context API
- CSS Contain Level 3 - delta spec
It also updates the URL of the CSS Cascade Level 6 spec, also published as FPWD this week.

Add 3 FPWD

---

specs.json
src/compute-shorttitle.js
test/compute-shorttitle.js

HTTP/1.1 spec titles were incorrectly shortened as "HTTP/1.1" (see #364). With this update, they get shortened as "HTTP/1.1 [module name]".
This update also explicitly sets the short title of a couple of IETF specs in specs.json as they did not produce suitable short titles.
Short titles could still be further improved and shortened in some cases, but they should at least be correct.

Improve short title logic for IETF specs

---

specs.json
src/data/monitor.json

The Autoplay Policy Detection document is being developed in the Media Working Group.
This update also updates the name of the Raw Sockets WICG repository, renamed from `raw-sockets` to `direct-sockets`, in the monitor list. Implementation plans are still unclear for the API.
Fixes #464.

Add Autoplay Policy Detection

---

README.md
schema/definitions.json
src/build-index.js
src/fetch-info.js
test/fetch-info-w3c.js
test/index.js

This adds a `title` and a `shortTitle` property to `series` that contain version-less versions of the spec's title and short title. The version-less version is retrieved from the W3C API for /TR specs, and computed by dropping the level from the spec's title otherwise.
When a `shortTitle` is set explicitly for the spec in `specs.json`, that title is used to compute the series' short title. This makes it possible to compute short titles such as "WebRTC" or "ECMAScript" instead of more verbose ones.
Close #359.
(CI tests will fail because the PR places additional constraints on the updated `index.json` file but does not contain the updated `index.json` file)

Add series titles to all specs

---

index.json
specs.json
src/build-index.js

Previous update introduced `series.shortTitle` but the level was incorrectly kept at the end of the series short title in some cases.
Explicit short titles that get set in specs.json also need to be consistent for the code to generate consistent series short titles.
Note that both issues are correctly detected and reported by the "has consistent series info" test in `test/index.js`, which makes sure that the series info is the same for all specs in a series.

Always drop level from series shortTitle

---

src/extract-pages.js

Build sometimes fails with a 500 internal server error in the extract pages module. That error was correctly reported but did not include the URL of the spec that triggered the error, making it hard to know which spec is causing troubles.

Improve error messages for the extract pages module

---

test/index.js

The W3C API now returns the right title for the spec, so exception-to-the-rule is no longer needed.

[test] Drop temp exception for fingerprinting-guidance title

---

specs.json
src/data/ignore.json

also ignore specs from Spatial Data on the Web WG, and xml-entities spec

Add Region Capture spec

---

specs.json

Both specs have moved to stage 4 and are now part of Ecma402.

Drop Intl.displaynames and Intl.Segmenter, merged in Ecma402

---

specs.json
src/data/ignore.json

The randomUUID method was merged in the WebCrypto API spec, see:
https://github.com/w3c/webcrypto/pull/285
This update adds the WICG repository to the ignore list.

Drop UUID incubation, now integrated in WebCrypto API

---

schema/specs.json
specs.json

Via https://github.com/w3c/browser-specs/issues/488#issuecomment-1027908030
The specs don't strictly follow the same overall structure as other TC39 proposals, and the headings they contain would not make particularly good titles in any case.
The titles are based on the ones advertized in:
https://tc39.es/proposal-intl-numberformat-v3/

Force title for TC39 Intl proposals

---

.github/workflows/build.yml
.github/workflows/check-base-url.yml
.github/workflows/lint.yml
.github/workflows/monitor-specs.yml
.github/workflows/report-new-specs.yml

The `workflow_dispatch` trigger allows admins to run the job manually through GitHub's admin UI instead of having to wait for the job to run based on other automatic triggers.
The update also puts the job's name first when that was not already the case.

Add "workflow_dispatch" where possible

---

src/prepare-release.js
src/release-package.js
src/request-pr-review.js

Jobs get both a `config.json` file (without a GitHub token) and a GitHub token provided as an environment variable. The scripts assumed that, whenever `config.json` existed, it would contain the GitHub token.

Fix the logic that retrieves GH_TOKEN env variable

---

src/bump-packages-minor.js
src/prepare-release.js

- Fixes the minor version bump logic. When a `return` statement returns something, that something must appear on the same line... The `isMinorBumpNeeded` function always returned a result that evaluated to `false` in practice. The function now also uses the `xxx@latest` branches as basis for comparison so as to compare the current list with the list that was last published.
- Fixes handling of "static" files in diff: The `README.md` and `LICENSE.md` should not change much and cannot be easily integrated in the diff without triggering markdown formatting issues. They are now reported separately at the beginning of the diff as "Files that changed" without details as to what changed.

Fix release workflow

---

.github/workflows/build.yml

Yet another release job fix ;)
Build job currently fails because the minor version bump logic needs to access the `xxx-specs@latest` branches, and the checkout action defaults to only retrieving the latest commit. This update tells the job to retrieve the whole repo history.

Fix release workflow: checkout all branches

---

src/bump-packages-minor.js

This update makes the script look for the fullname of the remote ref for `web-specs@latest` and `browser-specs@latest`. On top of being more accurate (no point basing the logic on a commit that only exists locally), this is needed when the repo is cloned from scratch and does not have local versions of these branches, which is typically what happens in a job.
This update also drops the escaping which I don't think is needed.
See additional context in: https://github.com/w3c/browser-specs/pull/504#issuecomment-1034062322

Minor version bump script: use full remote ref name

---

src/release-package.js

The release job failed to run the prepare script, so updates to README and `index.json` file was not present in the released package.
I wouldn't be surprised if the job that creates pre-release PRs fails next time due to released packages no longer containing index.json. I'll release a new version manually. I don't think there is a way to unpublish an NPM package unfortunately (we can just flag it as deprecated)
Edit: There is, I'll unpublish the versions.
Edit2: There isn't, we don't meet the [unpublishing criteria](https://docs.npmjs.com/policies/unpublish).

Fix release packages job: prepare files first!

---

.github/workflows/build.yml

This update makes the build job ignore pushes to main that touch on the `package.json` files under `packages`, to avoid triggering the job when pre-release PRs get merged.
Updates on tests are also ignored. If we really need to run the job after a test got updated, this can be done manually through GitHub's UI.

Don't run build job when pre-release PR gets merged

---

CONTRIBUTING.md
README.md
src/build-diff.js
src/build-index.js

This adds a new command-line tool `src/build-diff.js` that can be used to generate only the specs that have changed in `specs.json` between two commits.
For instance, to compute the diff between the current updated (but not committed) list of specs in `specs.json` and the one at HEAD, run:
```
node src/build-diff.js working HEAD
```
... where `working` is a special ref that means: the version of `specs.json` in your working folder, and `HEAD` is Git's HEAD. Any Git reference may be used, such as a commit ID (SHA).
The tool outputs a JSON object with `added`, `updated` and `deleted` properties. If you rather want it to spit out the new `index.json` file, add a `full` parameter, as in:
```
node src/build-diff.js working HEAD full
```
... which you could redirect to `index.json` and follow …

Add build-diff CLI to get a glimpse of updated data

---

src/data/monitor.json

The spec purports to add more advanced easing function, but right now doesn't have any actual change to level 1; putting in monitoring since I'm not sure it will be a full spec vs a delta once the changes start coming in
closes #524

Add CSS Easling Level 2 to monitor list

---

specs.json

This PR enables "exported" terms in MiniApp specs to be automatically cross-referenced using https://respec.org/xref/

Add miniapp specs

---

src/data/ignore.json

Repo is a placeholder for now; it may be that it should be added to web-specs eventually, but since we already have adpt and imsc-* in ignore, they would probably be added as a cluster in any case

Add dapt repo to ignore list

---

CONTRIBUTING.md
README.md
packages/browser-specs/package.json
packages/web-specs/package.json
schema/definitions.json
schema/index.json
schema/specs.json
specs.json
src/build-index.js
src/compute-currentlevel.js
src/compute-prevnext.js
src/compute-shortname.js
src/lint.js
test/compute-currentlevel.js
test/compute-shortname.js
test/index.js
test/lint.js
test/specs.js

This new composition level is meant for specs that are created as temporary forks of base specifications. First (and only so far) spec in that category is the "WebAssembly JavaScript Interface: Exception Handling" specification, as described in https://github.com/w3c/browser-specs/issues/508.
This will require a major version bump as this changes the semantics of the `seriesComposition` property.
(I'll work on an update to Reffy to handle fork specs)

Add new composition level: "fork"

---

.github/workflows/build.yml
.github/workflows/check-base-url.yml
.github/workflows/lint.yml
.github/workflows/monitor-specs.yml
.github/workflows/release-package.yml
.github/workflows/report-new-specs.yml
.github/workflows/request-pr-review.yml

Jobs were still using Node.js v14, which works fine for the scripts, but comes with a version of npm that does not support version 2 of the file format for `package-lock.json`. On top of that, a couple of scripts were running `npm install` instead of `npm ci`, and former updates `package-lock.json` when needed. This could trigger the creation of pull requests that included the `package-lock.json` file whereas they shouldn't as in #539.
This update makes all jobs switch to Node.js v16 (and ubuntu-latest, which seems like a safe setting to use) and use `npm ci` to install dependencies.

Make all jobs use Node.js v16 and "npm ci"

---

specs.json

see also https://github.com/w3c/browser-specs/pull/542#pullrequestreview-903950652
output of build-diff:
```json
{
"added": [
{
"url": "https://wicg.github.io/navigation-api/",
"shortname": "navigation-api",
"series": {
"shortname": "navigation-api",
"currentSpecification": "navigation-api",
"title": "Navigation API",
"shortTitle": "Navigation API",
"nightlyUrl": "https://wicg.github.io/navigation-api/"
},
"groups": [
{
"name": "Web Platform Incubator Community Group",
"url": "https://www.w3.org/community/wicg/"
}
],
"nightly": {
"url": "https://wicg.github.io/navigation-api/",
"repository": "https://github.com/wicg/navigation-api",
},
"title": "Navigation API",
"source": "spec",
"shortTitle": "Navigation API", …
```

Replace app-history with navigation-api

---

src/data/monitor.json

Add the spec and not the repo to avoid looking at the wrong spec for a fix:
https://github.com/w3c/browser-specs/issues/558#issuecomment-1073628769

Add clreq-gap to monitor list

---

src/compute-repository.js
src/fetch-groups.js
src/fetch-info.js
src/octokit.js
src/throttle.js

This adds throttling to network requests that used to be issued in parallel and that did not have explicit throttling, so as to be more gentle with web servers that the code needs to gather info from.
The `throttle` module exports a generic function that can be used to throttle another function to a maximum number of concurrent tasks. This module is used to throttle parallel requests to the W3C API server (in the hope that this can prevent 503 failures that we keep receiving), and to JSDOM (in the hope that being more gentle with the draft CSS server may help with its stability).
Code that uses Octokit now always goes through the throttled version as well.
Note that throttling is not used in `fetch-groups` simply because that module does not send requests in parallel for now (it uses a …

Throttle network requests

---

specs.json

This PR adds https://fs.spec.whatwg.org/ to the spec list.
As part of this PR to MDN BCD: https://github.com/mdn/browser-compat-data/pull/15537

Add WHATWG File System API

---

src/data/monitor.json

Both specs are now in the list (see #565 for the File System API), no need to have them in the monitoring list anymore.

Drop whatwg/fs and whatwg/websockets from monitoring file

---

test/fetch-groups-w3c.js

Reflects the new home page URL for the Web Apps WG, which is used in tests to check the link with the W3C API.

[tests] Update URL of Web Apps WG home page

---

README.md
test/index.js

The source of the spec is not in the default branch of the repository, and we don't have any easy way to point at another branch for now.
This update also adjusts the README (in practice, the Patent Policy document was already an exception)

Relax the sourcePath test for TC39 Decorators proposal

---

src/data/monitor.json

Fixes #582. No published content for now, the spec only exists in a Google doc.

Monitor tc39/proposal-regexp-set-notation

---

specs.json

Adopted by the Second Screen Working Group. Fixes #584.
```json
{
"added": [
{
"url": "https://w3c.github.io/window-placement/",
"shortname": "window-placement",
"series": {
"shortname": "window-placement",
"currentSpecification": "window-placement",
"title": "Multi-Screen Window Placement",
"shortTitle": "Multi-Screen Window Placement",
"nightlyUrl": "https://w3c.github.io/window-placement/"
},
"groups": [
{
"name": "Second Screen Working Group",
"url": "https://www.w3.org/2014/secondscreen/"
}
],
"nightly": {
"url": "https://w3c.github.io/window-placement/",
"repository": "https://github.com/w3c/window-placement",
"sourcePath": "index.bs",
},
"title": "Multi-Screen Window Placement",
"source": "spec", …
```

Add Multi-Screen Window Placement spec

---

.github/workflows/monitor-specs.yml
.github/workflows/report-new-specs.yml

A PR created as "draft" requires an extra manual step since it cannot be merged directly. The PRs created by the jobs need reviewing and may need to be amended, but they aren't drafts in the sense that the job is not going to update them later on with a more complete PR.

Jobs: Create PR without a "draft" status

---

specs.json
src/data/monitor.json

The WICG/origin-policy proposal was put on hold, see current README:
https://github.com/WICG/origin-policy/blob/2683f92226052dd363b84620247cdb5f949a4b75/README.md
WASM level 2 specs replace level 1. Cannot easily add WASM Core Level 2 for now because its multipage formatting and weird section numbering scheme likely requires changes to our extraction logic.
Fixes #590.
```json
{
"added": [
{
"url": "https://www.w3.org/TR/wasm-js-api-2/",
"shortname": "wasm-js-api-2",
"series": {
"shortname": "wasm-js-api",
"currentSpecification": "wasm-js-api-2",
"title": "WebAssembly JavaScript Interface",
"shortTitle": "WebAssembly JavaScript Interface",
"releaseUrl": "https://www.w3.org/TR/wasm-js-api/",
"nightlyUrl": "https://webassembly.github.io/spec/js-api/"
}, …
```

Move origin-policy to monitor, add WASM 2 specs except Core

---

specs.json

Spec was published as first public working draft last week.
Note the change of spec shortname from `mediacapture-handle-identity` to `capture-handle-identity` (and the inconsistency with other similar specs that had `mediacapture` as prefix, bouh).
Fixes #608.
Diff that this introduces:
```json
{
"added": [
{
"url": "https://www.w3.org/TR/capture-handle-identity/",
"shortname": "capture-handle-identity",
"series": {
"shortname": "capture-handle-identity",
"currentSpecification": "capture-handle-identity",
"title": "Capture Handle - Bootstrapping Collaboration when Screensharing",
"shortTitle": "Capture Handle - Bootstrapping Collaboration when Screensharing",
"releaseUrl": "https://www.w3.org/TR/capture-handle-identity/",
"nightlyUrl": …
```

Update URL for Media Capture Handle Identity

---

specs.json

Via https://github.com/w3c/webref/issues/601
Spec was published in 2019 as a Retired Group Note.

Drop retired Selectors Non Element spec

---

specs.json

Fixes #621
Note the Attribution Reporting API replaces the Conversion Measurement API
(same spec with different shortname and title)
Diff:
```json
{
"added": [
{
"url": "https://wicg.github.io/attribution-reporting-api/",
"shortname": "attribution-reporting-api",
"series": {
"shortname": "attribution-reporting-api",
"currentSpecification": "attribution-reporting-api",
"title": "Attribution Reporting",
"shortTitle": "Attribution Reporting",
"nightlyUrl": "https://wicg.github.io/attribution-reporting-api/"
},
"groups": [
{
"name": "Web Platform Incubator Community Group",
"url": "https://www.w3.org/community/wicg/"
}
],
"nightly": {
"url": "https://wicg.github.io/attribution-reporting-api/",
"repository": …
```

Adjust URLs of specs that migrated or got published to TR

---

specs.json

WOFF 2.0 does not replace WOFF 1.0. It just defines a second version of the file format. This adds WOFF 1.0 to the list.
WOFF 1.0 and WOFF 2.0 are part of the same series, which seems good. The shortname for WOFF 1.0 is `WOFF` because that is what the W3C API returns. Similarly, WOFF 1.0 is flagged as being the current specification for the series because that is the current specification returned by the W3C API for the specification series `WOFF` (and what people get when they browse https://www.w3.org/TR/WOFF/ ).
If that seems wrong, the info needs fixing in the W3C API.
Note that separating the specs entirely to create different spec series makes the build process fail because specs with TR URLs are supposedly managed by the W3C API, and there are no series named `WOFF1` and `WOFF2`. …

Add WOFF 1.0

---

specs.json
test/index.js

Add the latest revision of the Source Map spec to the list, using the readable HTML version of the spec published by sourcemaps.info. The actual spec is in a Google Doc but there is no easy way to extract content automatically from a
canvas-based Google Doc:
https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k
Organization and group are set to "sourcemaps.info" for lack of better choice. Also note the need to relax a couple of tests as there is no real repository for the spec (there is one for sourcemaps.info, but that's for the site itself, not for raising issues against the spec).
Closes #618.
This will add the following entry to the list:
```json
{
"url": "https://sourcemaps.info/spec.html",
"shortname": "sourcemap",
"series": { …
```

Add Source Map spec to the list

---

src/find-specs.js

From time to time, final slash may be missing in URLs of editor's drafts that the program gets from the W3C API. This update makes the code ignore the final slash when it compares URLs it finds in GitHub repos and URLs it gets from the W3C API.

Find new specs: Match on URLs without a final slash

---

specs.json

Fixes #633.
Diff:
```json
{
"url": "https://tc39.es/proposal-symbols-as-weakmap-keys/",
"shortname": "tc39-symbols-as-weakmap-keys",
"series": {
"shortname": "tc39-symbols-as-weakmap-keys",
"currentSpecification": "tc39-symbols-as-weakmap-keys",
"title": "Symbol as WeakMap Keys Proposal",
"shortTitle": "Symbol as WeakMap Keys",
"nightlyUrl": "https://tc39.es/proposal-symbols-as-weakmap-keys/"
},
"organization": "Ecma International",
"groups": [
{
"name": "TC39",
"url": "https://tc39.es/"
}
],
"nightly": {
"url": "https://tc39.es/proposal-symbols-as-weakmap-keys/",
"repository": "https://github.com/tc39/proposal-symbols-as-weakmap-keys",
},
"title": "Symbol as WeakMap Keys Proposal",
"source": "spec",
"shortTitle": "Symbol as WeakMap …
```

Add TC39 Symbol as WeakMap Keys proposal

---

specs.json
src/data/ignore.json

"COEP:credentialless merged into the HTML and Fetch specification."
https://github.com/WICG/credentiallessness/#obsoletion-notice

Drop credentiallessness, now merged in HTML and Fetch

---

src/data/monitor.json

The CHIPS spec is still empty and css-color-6 currently displays a "Not ready for implementation" banner.
This fixes #642.

Monitor CHIPS and css-color-6

---

specs.json

The proposed Visual Viewport API has been merged into CSSOM View:
https://github.com/w3c/csswg-drafts/issues/6339

Drop Visual Viewport API (merged in CSSOM View)

---

specs.json
src/data/ignore.json

Fixes #653
Also ignores WICG/visual-viewport (spec dropped from browser-specs last week
after it was merged into CSSOM View)
New specs:
```json
{
"url": "https://drafts.csswg.org/css-variables-2/",
"shortname": "css-variables-2",
"series": {
"shortname": "css-variables",
"currentSpecification": "css-variables-2",
"title": "CSS Custom Properties for Cascading Variables",
"shortTitle": "CSS Variables",
"nightlyUrl": "https://drafts.csswg.org/css-variables/"
},
"seriesVersion": "2",
"shortTitle": "CSS Variables 2",
"groups": [
{
"name": "Cascading Style Sheets (CSS) Working Group",
"url": "https://www.w3.org/Style/CSS/"
}
],
"nightly": {
"url": "https://drafts.csswg.org/css-variables-2/",
"repository": "https://github.com/w3c/csswg-drafts", …
```

Add css-variables-2, TR url of window-placement

---

specs.json

The spec dropped the level from its shortname and the link to the Editor's Draft no longer needs to be explicitly specified. This fixes #665.

Adjust URL of Service Workers

---

specs.json

Version 1.0 will soon be published as W3C Recommendation, the working group has started work on version 1.1. Fixes #674.
This will update the Payment Request entry with the following info:
```json
{
"url": "https://www.w3.org/TR/payment-request-1.1/",
"shortname": "payment-request-1.1",
"series": {
"shortname": "payment-request",
"currentSpecification": "payment-request-1.1",
"title": "Payment Request API",
"shortTitle": "Payment Request API",
"releaseUrl": "https://www.w3.org/TR/payment-request/",
"nightlyUrl": "https://w3c.github.io/payment-request/"
},
"seriesVersion": "1.1",
"shortTitle": "Payment Request API",
"groups": [
{
"name": "Web Payments Working Group",
"url": "https://www.w3.org/Payments/WG/"
}
],
"release": {
"url": …
```

Target version 1.1 of Payment Handler spec

---

specs.json

Temporary fix to be able to resume data curation in webref, pending proper fix on CSS WG side and possible hardcoded handling (see #675).

Force ED URL of css-color-4

---

specs.json
src/data/ignore.json
test/index.js

Adds JSON-LD syntax, api and framing specs to the list of specs not targeted at browsers.
See related request in:
https://github.com/w3c/respec/issues/4243
Build code gets confused by the versioning scheme used in the specs: code expects version number to appear last whereas JSON-LD specs have version numbers within the title. Hence the explicit series shortnames in `specs.json` and the hardcoded test exception for the series title.
This will add the following info to the list:
```json
{
"url": "https://www.w3.org/TR/json-ld11-api/",
"shortname": "json-ld11-api",
"series": {
"shortname": "json-ld-api",
"currentSpecification": "json-ld11-api",
"title": "JSON-LD Processing Algorithms and API",
"shortTitle": "JSON-LD Processing Algorithms and API",
"releaseUrl": …
```

Add JSON-LD specs to (non-browser) list

---

src/data/ignore.json
src/find-specs.js

Closes #680. False positive as list now contains v1.1 of the spec.

Ignore older version of Payment Request

---

specs.json
src/compute-shortname.js
src/determine-testpath.js
src/parse-spec-url.js
test/compute-repository.js
test/compute-shortname.js
test/fetch-groups.js

All https://www.khronos.org/registry/ URLs now redirect to https://registry.khronos.org/ equivalents.

Update all WebGL URLs

---

specs.json

I first tried just adding only the https://www.rfc-editor.org/rfc URLs for these — without also explicitly specifying the “nightly” URLs — but after running “npm run build”, I found that the build script doesn’t automatically pick up the https://httpwg.org/specs URLs as the nightly URLs.

Update HTTP Core spec URLs (RFCs 9110, 9111, 9112, 9113, 9114)

---

specs.json

Discontinued as described in https://w3c.github.io/payment-method-basic-card/

Remove Payment Method: Basic Card

---

specs.json

Spec adopted by the CSS WG. Fixes #699.
This will add:
```json
{
"url": "https://drafts.csswg.org/css-shared-element-transitions-1/",
"shortname": "css-shared-element-transitions-1",
"series": {
"shortname": "css-shared-element-transitions",
"currentSpecification": "css-shared-element-transitions-1",
"title": "CSS Shared Element Transitions",
"shortTitle": "CSS Shared Element Transitions",
"nightlyUrl": "https://drafts.csswg.org/css-shared-element-transitions/"
},
"seriesVersion": "1",
"groups": [
{
"name": "Cascading Style Sheets (CSS) Working Group",
"url": "https://www.w3.org/Style/CSS/"
}
],
"nightly": {
"url": "https://drafts.csswg.org/css-shared-element-transitions-1/",
"repository": "https://github.com/w3c/csswg-drafts", …
```

Add CSS Shared Elements Transitions

---

src/build-diff.js

branch names are case sensitive (in linux at least)

Use uppercase HEAD in diff script

---

specs.json

Code cannot find the folder in the CSS WG repo because for some reason the folder name does not include the spec level.

Add sourcePath for CSS Viewport

---

CONTRIBUTING.md
README.md
schema/definitions.json
src/build-index.js
test/index.js

This records the `w3c.github.io` URL for CSS drafts in a new `alternateUrls` property under `nightly`. See context in #704.
That property is an array as the mechanism could be used to record nightly URLs used by a spec throughout its development. The code automatically adds the w3c.github.io URL for CSS drafts.
One possible question: A spec already published in /TR could get a new shortname. Since the array is under `nightly`, this cannot really be used to record the previous /TR URL. Should this `alternateUrls` property rather be moved to the root (but then how to distinguish between alternate URLs for the nightly and release versions of the spec)? Or would we add an `alternateUrls` property under `release` as well if we ever want to track that?
Notes:
- creating the PR as draft as I …

Add a new alternateUrls property and use it for CSS drafts

---

schema/definitions.json
specs.json
src/compute-shortname.js
test/index.js

This adds the FIDO Client to Authenticator Protocol spec to the list, following discussions in #708.
The latest revision of the spec seems to be the Proposed Standard, not the review draft mentioned in the issue. This adds the version that includes errata.
Organization and group info are explicitly provided in `specs.json`. We may consider custom logic when and if we add more FIDO specs.
The shortname used by the FIDO Alliance uses a slightly different convention than other shortnames, adding a `v` before the version number: `fido-v2.1`. The shortname schema had to be relaxed accordingly.
Similarly, the filename schema had to be relaxed to also accept `.` characters.
Conceptually, these schema changes are breaking. Practically speaking, should we still consider them as minor changes?
The …

Add FIDO CTAP spec to the list

---

src/build-index.js

This adds the alternate series URL to the `alternateUrls` list for CSS drafts.
The alternate series URL is only added when the entry under consideration is the current level in the series. This guarantees that an alternate series URL appears only once in the resulting list.
This fixes #720 by implementing option 3 discussed there: "Add the series alternate URL directly to `nightly.alternateUrls`".

Complete alternateUrls with series URL for CSS drafts

---

specs.json
src/compute-repository.js
test/index.js

This adds a test to ensure that we cannot have two different nightly versions of a spec that target the same repo and source path.
This typically happened with SVG11 and SVG2. The SVG11 entry incorrectly reported that its source is to be found in the w3c/svgwg repository. This update drops the association with that repository... and updates the underlying code in `compute-repository` not to take for granted that hypothetical repositories returned by `parseSpecUrl` actually exist.
This fixes #418.

Test unicity of sourcePath and fix duplication in SVG11 entry

---

specs.json

This switches the canonical URL of "Trusted Types" and "A Well-Known URL for Changing Passwords" to the /TR URL now that these specs have been published as First Public Working Drafts.

Reflect publication as FPWD of webappsec specs

---

specs.json
src/build-index.js
src/fetch-info.js
test/index.js

3 updates in 1:
- [Rename css-shared-element-transitions-1 to css-view-transitions-1](https://github.com/w3c/browser-specs/commit/3faf1fc7000ff9eefa76ba9a75781366ce2e2399)
- [Fetch alternate URL for CSS drafts](https://github.com/w3c/browser-specs/commit/37d1020c11b33529745abaea33c0dae25fe3d086)
- [Use draft shortname for alternateUrls of CSS specs](https://github.com/w3c/browser-specs/commit/a659bcb19e504ecb65d63d57a5748e74d5735d53). This fixes #730

Adjust alternate urls

---

specs.json
src/data/ignore.json

- Resource Timing no longer uses levels.
- Image Maps got folded into HTML and now redirects to it.
This fixes #736, #737.

Adjust URL of Resource Timing, ignore Image Maps

---

src/data/monitor.json

Specs are currently empty. We may want to add them (as non-browser specs) later on. Via #746.

Add specs from RCH WG to monitor list

---

specs.json
src/data/ignore.json
src/data/monitor.json

This update also adds the `resource-timing-1` spec to the ignore list (we have `resource-timing` in the list, level version exists for historical reasons).
Fixes #751.

Add TC39 RegExp modifiers, monitor Pending Beacon

---

specs.json

[RFC8288](https://www.rfc-editor.org/rfc/rfc8288) is now a proposed standard, would be nice to have it here. Contents of the RFC (Link header) already implemented in Chrome.

Add RFC8288 support

---

specs.json

This adds RFC9163 (published a few months ago from the Expect-CT draft) and the Digest headers draft to the list, as requested in #339.
New entries:
```json
{
"url": "https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-digest-headers",
"shortname": "digest-headers",
"series": {
"shortname": "digest-headers",
"currentSpecification": "digest-headers",
"title": "Digest Fields",
"shortTitle": "Digest Fields",
"nightlyUrl": "https://httpwg.org/http-extensions/draft-ietf-httpbis-digest-headers.html"
},
"organization": "IETF",
"groups": [
{
"name": "HTTP Working Group",
"url": "https://datatracker.ietf.org/wg/httpbis/"
}
],
"nightly": {
"url": "https://httpwg.org/http-extensions/draft-ietf-httpbis-digest-headers.html",
"repository": …
```

Add Expect-CT RFC and Digest headers draft

---

specs.json

I believe that this document is eligible under criterion 4, specifically "*it contains informative content that other specs often need to refer to (e.g. guidelines from horizontal activities such as accessibility, internationalization, privacy and security)*." I discovered that it was missing by trying to reference the `dfn` for `testable assertion` which I believe to be a rather central concept.

Add https://www.w3.org/TR/test-methodology/

---

specs.json
test/index.js

Also adds these specs (and test-methodology) to the list of specs for which we should not expect to find any repository or source path, because they don't have any.
This would fix #776.

Add rdf-canon and RDF specs it references

---

specs.json

Fixes #788.
It is not entirely clear whether the proposal will be officially adopted and eventually published as an RFC, but it seems still somewhat "active" in 2022 (a couple of discussions in the repository), and supported in Chrome.
Linking the proposal to the HTTP Working Group, since that's what the draft says, although the same comment applies here: it is not entirely clear whether the group will officially adopt the draft.
Note: the nightly URL is set to the better-looking HTML version. The URL contains the document's version and will need to be adjusted if a new draft gets published.
This would add the following entry:
```json
{
"url": "https://datatracker.ietf.org/doc/html/draft-davidben-http-client-hint-reliability",
"shortname": …
```

Add Client Hint Reliability IETF draft

---

specs.json

The title of the spec was recently changed from "The Screen Orientation API" to "Screen Orientation". The series' title has not yet been updated in the W3C API though. This update updates the series title in browser-specs while this gets fixed in the W3C API.

Force series title for Screen Orientation

---

specs.json
src/data/monitor.json

Draft spec is now correctly rendered by CSS server. Fixes #792.

Add CSS Link Parameters spec

---

src/check-base-url.js

The job that checks base URLs already had an exception-to-the-rule for IETF specs but the latest one uses a slightly different pattern.
This fixes #793 (by making the tool not report the spec anymore)

Adjust test on base URL for new IETF spec

---

specs.json
src/compute-categories.js
src/compute-shortname.js
src/data/ignore.json
src/fetch-groups.js
src/parse-spec-url.js
test/compute-categories.js
test/compute-shortname.js

This adds the "Writing Promise-Using Specifications" TAG finding to the (non-browser) list to reduce the gap between specs in Shepherd and specs in Webref, as discussed in https://github.com/tabatkins/bikeshed/issues/2431
The TAG was added to the list of non-browser groups to make sure TAG Findings get classified as non-browser specs.
This also adds the code needed to extract findings shortnames and repositories, so that we can be more systematic about these specs from now on.
The update also fixes the code that looked for a non-browser group in the list of groups that produced the spec. That code assumed that whenever there's a non-browser group in the list, the spec is not targeted at browsers. CSS Typed OM is a counter-example (jointy developed by the CSS WG and the TAG). The fix …

Add promises-guide, make code handle TAG findings

---

src/fetch-groups.js
test/fetch-groups.js

The call to `continue` was the result of a ill-inspired copy-and-paste. This update also creates a dedicated test.

Make sure organization is set for TAG findings

---

README.md
index.json
schema/definitions.json
src/fetch-info.js
test/fetch-info-w3c.js
test/fetch-info.js

This makes the code also report on the status of the nightly and release versions of each spec in the list.
This is intended to be used for analysis, but also to flag specs automatically as "unofficial" afterwards (planned for a separate PR).
Currently, that will create the following statuses:
Release statuses:
- Candidate Recommendation Draft: 33 specs
- Candidate Recommendation Snapshot: 29 specs
- Draft Note: 14 specs
- Draft Registry: 1 specs
- First Public Working Draft: 32 specs
- Note: 3 specs
- Proposed Recommendation: 1 specs
- Recommendation: 27 specs
- Retired: 2 specs
- Working Draft: 131 specs
Nightly statuses:
- A Collection of Interesting Ideas: 2 specs
- Draft Community Group Report: 63 specs
- Editor's Draft: 401 specs
- Experimental: 2 specs
- Informational: 1 specs
- …

Add new "status" property to "nightly" and "release"

---

specs.json

The /TR version of the spec has been discontinued and redirects to the WHATWG version.
This will update the "encoding" entry to:
```json
{
"url": "https://encoding.spec.whatwg.org/",
"shortname": "encoding",
"series": {
"shortname": "encoding",
"currentSpecification": "encoding",
"title": "Encoding Standard",
"shortTitle": "Encoding",
"nightlyUrl": "https://encoding.spec.whatwg.org/"
},
"organization": "WHATWG",
"groups": [
{
"name": "Encoding Workstream",
"url": "https://encoding.spec.whatwg.org/"
}
],
"nightly": {
"url": "https://encoding.spec.whatwg.org/",
"status": "Living Standard",
"repository": "https://github.com/whatwg/encoding",
"sourcePath": "encoding.bs",
},
"title": "Encoding Standard",
"source": …
```

Switch to WHATWG URL for Encoding spec

---

CONTRIBUTING.md
README.md
index.json
schema/definitions.json
schema/index.json
schema/specs.json
specs.json
src/build-index.js
src/compute-standing.js
src/prepare-packages.js
test/compute-standing.js

Second take at #812.
This update creates a new `standing` category for specs whose status is "A Collection of Interesting Ideas" or "Unofficial Proposal Draft".
As usual, default rule can be overridden in `specs.json`. Done for font-metrics-api-1 and web-animations-2 because they define IDL that has already been included in Web Platform Tests.
The css-typed-om-2 spec will be the only one to get a `"pending"` standing for now.
Specs in pending status appear in the web-specs package but get filtered out of the browser-specs package.
The new status will make it possible to add a few additional unofficial CSS specs. To be done in a separate commit.

Add new "standing" property

---

.github/workflows/build.yml
.github/workflows/lint.yml
src/build-index.js
test/fetch-groups-w3c.js
test/fetch-info-w3c.js

There was a typo in the tests that checked groups: the code read the GitHub token in `config.json` under `githubToken` instead of under `GH_TOKEN` as done in `build-index.js` (we're not fantastically consistent with our naming conventions here, we use `w3cApiKey` for the API key, but `GH_TOKEN` for the GitHub token. Anyway)
This meant that the test request to the GitHub API was done without any authentication. Most of the time, that did not have any consequence, but CI tests now regularly fail at that step, probably because the GitHub API enforces limits more strongly.
In any case, it seems much much better to use the GitHub token that GitHub provides to actions rather than one we set by hand long time ago. I suspect that setting config.json as a secret was done at a time when we were not …

Retrieve W3C API key from environment, drop config.json

---

README.md
schema/definitions.json
specs.json
src/compute-repository.js
src/compute-standing.js
src/data/ignore.json
src/data/monitor.json
test/compute-standing.js
test/index.js

This update adds a new `discontinued` value to the `standing` property for specs that are still in the list for some reason (typically because other specs still reference terms and sections they define in informative prose), but whose development has been discontinued. Specs whose status is "Discontinued Draft" end up with a `discontinued` standing.
This affects DNT in the current (before this update) list. The spec will be filtered out of the `browser-specs` package as a result. That seems a good thing.
This update also adds CSS specs that are needed for cross-referencing purpose in Bikeshed, as requested in:
https://github.com/tabatkins/bikeshed/issues/2431#issuecomment-1373992354
New specs are either:
- discontinued specs such as selectors-nonelement-1, DOM-Level-2-Style
- older …

Add "discontinued" standing, add missing specs for Bikeshed

---

specs.json

Spec was published as First Public Working Draft last week. Fixes #816.
Change:
```json
{
"url": "https://www.w3.org/TR/web-locks/",
"shortname": "web-locks",
"series": {
"shortname": "web-locks",
"currentSpecification": "web-locks",
"title": "Web Locks API",
"shortTitle": "Web Locks API",
"releaseUrl": "https://www.w3.org/TR/web-locks/",
"nightlyUrl": "https://w3c.github.io/web-locks/"
},
"groups": [
{
"name": "Web Applications Working Group",
"url": "https://www.w3.org/groups/wg/webapps"
}
],
"release": {
"url": "https://www.w3.org/TR/web-locks/",
"status": "First Public Working Draft",
"filename": "Overview.html"
},
"nightly": {
"url": "https://w3c.github.io/web-locks/",
"status": "Editor's Draft",
"repository": …
```

Update canonical URL of web-locks to /TR URL

---

specs.json

The short title for Level 4 was explicitly set to drop "Basic". For consistency, we need to do the same thing with Level 3.

Fix short title of css-ui-3

---

specs.json
src/compute-repository.js
src/data/monitor.json

As requested in #822.
I'm not entirely clear whether the IETF work supersedes the WICG work and repo. I kept the `WICG/CHIPS` entry in the monitor list for now.
Change:
```json
{
"url": "https://datatracker.ietf.org/doc/html/draft-cutler-httpbis-partitioned-cookies",
"shortname": "partitioned-cookies",
"series": {
"shortname": "partitioned-cookies",
"currentSpecification": "partitioned-cookies",
"title": "Cookies Having Independent Partitioned State specification",
"shortTitle": "Cookies Having Independent Partitioned State specification",
"nightlyUrl": "https://dcthetall.github.io/CHIPS-spec/draft-cutler-httpbis-partitioned-cookies.html"
},
"organization": "IETF",
"groups": [
{
"name": "HTTP Working Group",
"url": "https://datatracker.ietf.org/wg/httpbis/"
} …
```

Add CHIPS IETF draft

---

src/build-index.js

The currently list asserts that `css-2022` is the current specification of the `CSS` series, even though, for us, the `CSS` series is different from the `css` series (the former contains the CSS 2.x specs, the latter contains the CSS snapshots).
This is because the W3C API considers that these series are just one series and returns `css-2022` as the current specification. This update makes sure that the code ignores the current specification returned by the W3C API when it does not belong to the same specification series for us.
This will make the code get back to `CSS22` as the current specification for the `CSS` series.

Ignore current spec from W3C API if series is different

---

specs.json

Underlying repository was renamed to local-network-access, previous URL redirects to the new one (and confuses browser-specs)
```json
{
"url": "https://wicg.github.io/local-network-access/",
"shortname": "local-network-access",
"series": {
"shortname": "local-network-access",
"currentSpecification": "local-network-access",
"title": "Private Network Access",
"shortTitle": "Private Network Access",
"nightlyUrl": "https://wicg.github.io/local-network-access/"
},
"groups": [
{
"name": "Web Platform Incubator Community Group",
"url": "https://www.w3.org/community/wicg/"
}
],
"nightly": {
"url": "https://wicg.github.io/local-network-access/",
"status": "Draft Community Group Report",
"repository": …
```

Update URL of Private Network Access spec

---

specs.json
src/data/ignore.json
src/data/monitor.json

The css-device-adapt-1 spec will be retired soon and replaced by css-viewport. We had already updated the entry to have css-viewport be the Editor's Draft of css-device-adapt-1 but that remains confusing. This update completely drops css-device-adapt-1.
See https://github.com/w3c/browser-specs/issues/837
New entry would be:
```json
{
"url": "https://drafts.csswg.org/css-viewport/",
"shortname": "css-viewport",
"series": {
"shortname": "css-viewport",
"currentSpecification": "css-viewport",
"title": "CSS Viewport",
"shortTitle": "CSS Viewport",
"nightlyUrl": "https://drafts.csswg.org/css-viewport/"
},
"groups": [
{
"name": "Cascading Style Sheets (CSS) Working Group",
"url": "https://www.w3.org/Style/CSS/"
}
],
"nightly": {
"url": …
```

Replace css-device-adapt-1 with css-viewport

---

.github/workflows/build.yml

Building the index when we push a change to the main branch is a nice idea in theory, but the build process consumes a lot of GitHub API requests and, due to GitHub API rate limits, can essentially only run once per hour. That does not work well when there is more than one pull request to merge.
The job can still be triggered manually through GitHub's admin interface.

Stop re-building the index on pushes to the main branch

---

specs.json

The EXT_clip_cull_distance extension is moving forward, dropping the `EXT` prefix in favor of a `WEBGL` prefix, as discussed in: https://github.com/KhronosGroup/WebGL/issues/3109
This update also adds the provoking_vertex extension, which was added to the WebGL repository 6 months ago, and moved to a `WEBGL` prefix a couple of months ago.
New entries:
```json
[
{
"url": "https://registry.khronos.org/webgl/extensions/WEBGL_clip_cull_distance/",
"shortname": "WEBGL_clip_cull_distance",
"series": {
"shortname": "WEBGL_clip_cull_distance",
"currentSpecification": "WEBGL_clip_cull_distance",
"title": "WebGL WEBGL_clip_cull_distance Extension Draft Specification",
"shortTitle": "WebGL WEBGL_clip_cull_distance Extension Draft",
"nightlyUrl": …
```

Update EXT_clip_cull_distance and add WEBGL_provoking_vertex extensions

---

README.md
specs.json
src/compute-series-urls.js
src/lint.js
test/compute-series-urls.js
test/lint.js

This makes `compositing-2` the current specification for `compositing`, as discussed in https://github.com/w3c/browser-specs/pull/848#issuecomment-1403172297
This will make the data report the following series info:
```json
{
"shortname": "compositing",
"currentSpecification": "compositing-2",
"title": "Compositing and Blending",
"shortTitle": "Compositing",
"nightlyUrl": "https://drafts.fxtf.org/compositing/",
"releaseUrl": "https://www.w3.org/TR/compositing/"
}
```
The `nightlyUrl` is good and returns Level 2. The `releaseUrl` returns the latest published version of the spec, which is Level 1. That's not the level that is deemed current, but then it is the latest published version.
README amended accordingly to clarify that `releaseUrl` is not always the current spec, and that …

Make compositing-2 current, fix series.releaseUrl logic

---

test/fetch-info-w3c.js
test/fetch-info.js

Bikeshed's documentation is used in tests as a canonical Bikeshed spec. The Bikeshed repo was moved last week and URL needs updating.

Update URL of Bikeshed spec in tests

---

specs.json

The Contact Picker API no longer uses a versioned shortname. Adjusting the URL accordingly.

Drop level from URL of Contact Picker API

---

src/check-base-url.js

We don't apply the "base URL must match nightly URL" rule for IETF drafts. The CHIPS spec lives in a separate repository, and wasn't considered to be excluded from that rule.
Closes #857.

Check base URL: add exception-to-the-rule for CHIPS spec

---

.github/candidate-specs.md

Link to the `monitor.json` file was broken.

Fix typo in candidate spec template

---

specs.json

HTTP header and JS API are implemented in Firefox, Brave and DuckDuckGo browsers.
Via #855.

Add Global Privacy Control spec

---

specs.json
src/build-index.js
src/compute-shortname.js
test/compute-shortname.js

This update adds 19 RDF/SPARQL 1.2 drafts to the list, as non-browser specs. It also makes the code cognizant of the RDF/SPARQL numbering and titling scheme.
Note that the shortnames are "invented" for now. They match those used within the specs themselves, so hopefully the working group will just continue to use that same pattern when it starts publishing specs to /TR: https://w3c.github.io/rdf-primer/spec/#related
Previous RDF 1.1 entries (concepts and semantics) were dropped in favor of the new ones. This means that the list does not contain any /TR document for RDF and SPARQL, but that seems fine to me. Previous ones did not respect the definitions data model and are thus "less interesting" in any case.
This update does not add the "What's new" and "Primer" specs (two for RDF, one for …

Add RDF 1.2 and SPARQL 1.2 drafts

---

src/data/ignore.json

As discused in #864. We may want to revisit that later on (but then we may want to revisit all groups, repos and specs in the ignore list that are flagged as "not targeted at browsers").

Add RDF/SPARQL primer and what's new notes to ignore list

---

specs.json

Merged previous PR #862 too fast, forgot to wait until a `w3c.json` file gets added to the repository, see pending PR:
https://github.com/privacycg/gpc-spec/pull/47

Re-add Global Privacy Control spec

---

specs.json

This adds the TC39 ArrayBuffer transfer proposal, which reached Stage 3.
Source of the spec is in a `spec.emu` file, like 3 other TC39 specs. That seemed a good occasion to turn the exception into a rule. The code now also looks for `spec.emu` when it searches the source of the spec.
Closes #870.
```json
{
"url": "https://tc39.es/proposal-arraybuffer-transfer/",
"shortname": "tc39-arraybuffer-transfer",
"series": {
"shortname": "tc39-arraybuffer-transfer",
"currentSpecification": "tc39-arraybuffer-transfer",
"title": "ArrayBuffer transfer",
"shortTitle": "ArrayBuffer transfer",
"nightlyUrl": "https://tc39.es/proposal-arraybuffer-transfer/"
},
"organization": "Ecma International",
"groups": [
{
"name": "TC39",
"url": "https://tc39.es/"
}
],
"nightly": {
"url": …
```

Add TC39 ArrayBuffer transfer, look at "spec.emu" for sourcePath

---

src/compute-repository.js

File update should have been part of previous commit. Needed to put `spec.emu` in the list of well-known source files for specs.

Consider spec.emu for sourcePath

---

specs.json

CSS 2023 snapshot just published to /TR. It replaces the 2022 version as the current snapshot. Older version kept in the list for now although we may want to drop it later on, e.g. next time we add a CSS snapshot.
Closes #877.

Add CSS 2023 snapshot to the list

---

specs.json

CSS Working Group decided to rename the spec, see: https://github.com/w3c/csswg-drafts/commit/d76c8ca2072af5b7571f79c40ccfc92b90c15fc3

Rename css-anchor to css-anchor-position

---

specs.json
src/data/ignore.json

Spec has now been fully integrated in HTML and Fetch.
(supersedes #791)

Drop Priority Hints from spec list

---

specs.json

The spec is being staged for publication to /TR and the status of the nightly version is currently "First Public Working Draft". I suspect the nightly draft will become an "Editor's Draft" after publication.
In the meantime, to unlock build, this update forces the status to what it used to be, meaning "Unofficial Proposal Draft".

Force status of Web Animations 2

---

specs.json
test/index.js

This forces the shortname of the CSS 2.1 spec to be `CSS2` instead of `CSS21` as requested in #879. This is consistent with /TR and Specref.
Some notes:
- In theory, `CSS2` is more an alias of `CSS2.1` than a real shortname. However we don't record aliases in browser-specs, only a spec shortname and the series shortname. Having `CSS2` as the series shortname seems wrong. We will lose `CSS21` as a result. I don't think that is really problematic in practice.
- The base URL could perhaps be `https://www.w3.org/TR/CSS2/` instead of `https://www.w3.org/TR/CSS21/`. However, the W3C API would still return `https://www.w3.org/TR/CSS21/` as being the release URL for the spec, so we would end up with a slight inconsistency (and a failed test).
- The Latest Editor's Draft in CSS 2.1 points to the …

Force shortname of CSS21 to be CSS2

---

specs.json
src/data/ignore.json

The spec is being integrated in HTML and no longer contains any useful content.

Drop Navigation API

---

specs.json

The status of the nightly version of CSS Animations 2 is currently set to "First Public Working Draft". Not such a big deal, but not one of the expected values per our JSON schema.
If this type of issues keeps re-appearing, we may want to do one of:
1. add logic to convert the status of nightly versions to "Editor's Draft" when needed
2. relax the JSON schema to also accept release statuses
3. keep on being strict and report issues to groups

Force nightly status of CSS Animations 2 to ED

---

specs.json

This update also drops the "Unofficial Proposal Draft" status for the nightly version. The spec still has a "Not ready for implementation" banner (including in the version published under /TR) but publication on the Rec track makes things official.

Update URL of Web Animations 2 to use FPWD URL

---

specs.json
src/data/ignore.json

Spec integrated in HTML. The ED now redirects to HTML, which makes Reffy think that Resource Hints is the HTML spec.
Via https://github.com/w3c/reffy/issues/1236

Drop Resource Hints from the list

---

specs.json

The proposal was renamed to Import Attributes, its URL updated, and more importantly the proposal was demoted to Stage 2 last month: https://github.com/tc39/proposals/commit/faa00dc13c48463a02dfe3aa6387b7082b41ce27
... which provides a practical example for:
https://github.com/w3c/browser-specs/issues/307#issuecomment-856606328

Drop TC39 Import Assertions proposal

---

specs.json

The spec was re-published with a new title and shortname: https://www.w3.org/TR/window-management/

Use new window-management shortname for window-placement

---

specs.json

Entries for RFC9110, RFC9111, RFC9112, RFC9113 and RFC9114 were explicitly forcing the use of `httpwg.org` URLs. That's not really useful since the `rfc-editor.org` URLs are just as readable. That also introduces hiccups because fragment IDs are not the same in both versions, as in: https://github.com/w3c/IFT/issues/143
This update drops the explicit mention. In practice, that means that the info in browser-specs will align itself with whatever is in Specref, and Specref has the appropriate logic (`httpwg.org` for old RFCs, `rfc-editor.org` for newer ones).
Looking at Webref data, this switch will only impact the FedCM spec. Other specs that reference the afore-mentioned RFCs do not link to sections.
Example of update that this will introduce:
```json
{
"url": …
```

Stop using httpwg.org URL for newish RFCs

---

specs.json

The title of the spec switched to "Scroll-driven Animations" but the series title in the W3C API is still the old one. Name will soon be fixed in the W3C API database. This temporary update is only meant to resume building so that a new package may be published.

Temporarily force series title for scroll-animations

---

specs.json

Title of the `turtledove` proposal changed to:
"Protected Audience (formerly FLEDGE)"
The code thinks that the text between parentheses is the short title since that's the usual convention. This update hardcodes the short title to "Protected Audience".

Adjust short title for Protected Audience

---

src/release-package.js

Same as in:
https://github.com/w3c/webref/pull/954
Not advertized in the list of breaking changes made in v2 AFAICT, but main function is no longer exported as default.

Adjust reference to npm-publish package

---

src/fetch-info.js

The `https://w3c.github.io/csswg-drafts/` URLs now redirect to `https://drafts.csswg.org/css-viewport/`, following: https://github.com/w3c/csswg-drafts/issues/8798
Using `w3c.github.io` URLs no longer makes sense as a result. On top of adding a redirection, it prevents build because the w3c.github.io URL for `css-page-4` is currently broken.

Stop using w3c.github.io URL to fetch CSS specs

---

specs.json

Note the update is also needed to fix a build issue, as the code gets confused by the `WD` status now returned by SpecRef for what the code expects to be the description of the Editor's Draft.

Update URLs of 16 RDF 1.2 specs published as FPWD

---

specs.json
src/data/monitor.json

Spec reached stage 3.
This update also adds the decorator metadata proposal to the monitor list because, even though the proposal reached stage 3, the actual spec just contains placeholder text for now.

Add TC39 float16array proposal

---

src/determine-filename.js

This update switches the order by which the code looks for spec filenames.
This follows from discussions about CSS drafts, which currently exist both as `Overview.html` and `index.html`, the latter being the most recent: https://github.com/w3c/csswg-drafts/issues/8899
This will de facto update the `filename` of all CSS drafts to `index.html`. Note that this will also update the `filename` of WebCrypto, which is a good thing because `Overview.html` actually redirects to `index.html` there.

Prefer index.html over Overview.html when detecting filenames

---

specs.json
test/fetch-groups-w3c.js

Published as First Public Working Draft this week.
The update also fixes the URL of the webapps WG's home page in tests (final slash added following website redesign).

Update URL of css-anchor-position-1

---

src/fetch-info.js
test/fetch-info.js

If [PR on Specref gets merged](https://github.com/tobie/specref/pull/750), browser-specs will start contributing specs to Specref. At the same time, it fetches info for bunch of other specs from Specref. For obvious reason, browser-specs must not use spec info from Specref for specs it actually contributes to Specref, otherwise we would not longer be able to track updates made to that spec.
Unfortunately, there is no way to know from Specref's API where a spec comes from (the API does not return the `source` property), so code needs to fetch the list of specs to discard directly from Specref's GitHub repository.

Filter out specs contributed to Specref

---

specs.json

Group Draft Note is not a "nightly" status. The spec has not been published to /TR yet, the status should switch back to "Editor's Draft" once that happens, as done for other SPARQL specs.

Fix nightly status of SPARQL 1.2 Concept

---

specs.json

Requested for integration in MDN browser-compat-data in #1012.
The spec has not yet been adopted by the PAT CG. Hence the "pending" standing.

Add Topics API, with a "pending" standing

---

specs.json

Spec about to be folded into the HTML spec.
Keeping the spec as "discontinued" for the interest of integration with Specref. Entry should get an `obsoletedBy` property that points to HTML once we have such a mechanism in place (see #1006).

Fix Close Watcher title and flag spec as discontinued

---

CONTRIBUTING.md
README.md
schema/definitions.json
schema/index.json
schema/specs.json
specs.json
test/index.js

The new optional `obsoletedBy` property makes it possible to identify specs that replace a given discontinued spec in the list, as discussed in #1006. The term `obsoletedBy` was preferred over `replacedBy` because the latter is not fantastic to convery the integration of a spec into another one, and because Specref uses that term.
The new optional `formerNames` property makes it possible to list former shortnames of a spec in browser-specs.
Both properties are useful, and needed, for browser-specs to act as a source of specs for Specref. Other projects may also use these properties to track a spec over time.
Both properties must be set in `specs.json` and are copied over to `index.json`.
This update sets the `obsoletedBy` property on the discontinued Close Watcher API spec to target the …

New `obsoletedBy` and `formerNames` properties

---

.github/workflows/build.yml
.github/workflows/check-base-url.yml
.github/workflows/lint.yml
.github/workflows/monitor-specs.yml
.github/workflows/release-package.yml
.github/workflows/report-new-specs.yml
.github/workflows/request-pr-review.yml

This should speed up installation of dependencies (this usually only takes a few seconds for browser-specs so speedup will remain limited) and save a bit of energy.
This update also switches to using `npm ci` everywhere instead of installing only required dependencies, for consistency across jobs.

Enable dependencies caching in jobs

---

specs.json

Spec is a "delta" spec that creates its own series, which we cannot easily capture without changing the data model or (implicit) guarantees enforced by tests.
Such breaking changes could be introduced later if we realize that we really need to capture the "delta" composition status of the spec.
See discussion in https://github.com/w3c/browser-specs/issues/1025
This will add the following entry to the list:
```json
{
"url": "https://drafts.csswg.org/css-borders-4/",
"shortname": "css-borders-4",
"series": {
"shortname": "css-borders",
"currentSpecification": "css-borders-4",
"title": "CSS Borders and Box Decorations",
"shortTitle": "CSS Borders and Box Decorations",
"nightlyUrl": "https://drafts.csswg.org/css-borders/"
},
"seriesVersion": "4",
"organization": …
```

Add css-borders-4 (as "full" spec for now)

---

package-lock.json
package.json
src/build-index.js
src/extract-pages.js
src/fetch-info.js
src/find-specs.js
test/extract-pages.js

Puppeteer is more heavy-weight but JSDOM cannot easily load specs and GitHub pages. This update:
- fixes the find-specs script (#1031)
- removes the dependency on the spec-generator service
Note: I validated that the new code produces the same results.

Replace JSDOM with Puppeteer throughout

---

specs.json

Via https://github.com/w3c/browser-specs/issues/1008
The update also includes specs that have already been merged into the 2024 edition of the EcmaScript specification, and internationalization proposals that have been merged into the 2024 edition of the ECMA-402 specification.

Flag TC39 proposals merged into main spec as obsolete

---

specs.json

I thought being lazy would work but since the source of the Editor's Drafts got moved to separate repositories (and since /TR versions have not yet been updated), the code cannot compute a meaningful `sourcePath`.
Also forcing the status of the ED of CSS Transitions 2, since it is currently set to FPWD, in preparation to publication to /TR.

Be explicit about URL and repository of MSE byte stream specs

---

schema/definitions.json
specs.json
src/find-specs.js

This update also relaxes the rule on the nightly status to also accept "Draft Registry". Technically speaking, that's sort of wrong because the nightly version should rather be an "Editor's Draf of a Draft Registry", but that seems uselessly picky.

Add Permissions Registry, consider registries in find-specs

---

specs.json

https://webassembly.github.io/spec/core/

Add WasmGC spec

---

specs.json

- Use /TR URL for css-transitions-2. Nightly status also back to normal
- Add Web Preferences API WICG proposal, currently flagged as "pending".
Fixes #1056

Update css-transitions-2, add Web Preferences API

---

specs.json

The ED currently reflects the /TR status and claims it is a CR Snapshot. Worth fixing in the ED perhaps but then that seems like a good candidate fight for another day...
(Note build will continue to fail due to unrelated broken links in the Network Error Logging entry, reported in https://github.com/w3c/network-error-logging/pull/163#issuecomment-1740365947)

Force nightly status of PNG spec

---

specs.json

Spec no longer comes as Level 1. Should fix #1078.

Update URL of network-error-logging

---

src/data/monitor.json

No `w3c.json` file yet. Closes #1076.

Add Controlled Frame proposal to monitor list

---

specs.json
src/data/ignore.json
src/data/monitor.json

- Add WebXR Plane Detection
- Add WebXR Meshing API
- Add WebXR Mesh Detection Module
- Add WebBluetooth Scanning API
- Add Managed Configuration API
- Add MathML4, as non browser spec
- Monitor Private Aggregation API (pending w3c.json at least)
- Ignore a few additional specs (not required as these specs are not found but that makes the rationale explicit)

Some updates based on #1008

---

specs.json
src/data/ignore.json
src/data/monitor.json

- Add No-Vary-Search proposal
- Add DPUB ARIA as non-browser spec
- Add DPUB AAM as non-browser spec
- Monitor iframe Credentialness, pending w3c.json fix
- Monitor p2p-webtransport, pending clarification of status
- Ignore Math AAM, no longer worked on
- Update ignore rationale for webpayments-http-messages
- Drop EPUB Working Group from ignore list

More updates based on #1008

---

src/data/ignore.json
src/data/monitor.json

Discussed in #1008. Both specs are referenced by HTML. Both specs are in a sorrow state with no plan to resume work in the foreseeable future. Adding them to the ignore list as a result.
We may want to revisit that if the situation evolves, but I don't think we should (or want ;)) to do that every 3 months.

Explicitly ignore execCommand and sourcing in-band track

---

src/fetch-info.js

This update makes the code use the same fetch options as Reffy, waiting until the page has fully loaded. This makes the code follow redirects implemented as a `<meta>` tag in particular (e.g. Close Watcher).
Note build will continue to fail for now because of the URL Pattern spec that currently returns "Testing" as content.

Wait until network is idle to account for redirects in meta tags

---

specs.json

Partially addresses #1088.
This would add the following entry to the list. Note that the code currently fails to extract the "Final Deliverable" status of the spec and rather says that it is an "Editor's Draft". That seems fine for now, but we should look into it when we address the other specs mentioned in #1088.
```json
{
"url": "https://aomediacodec.github.io/av1-avif/",
"shortname": "av1-avif",
"series": {
"shortname": "av1-avif",
"currentSpecification": "av1-avif",
"title": "AV1 Image File Format (AVIF)",
"shortTitle": "AVIF",
"nightlyUrl": "https://aomediacodec.github.io/av1-avif/"
},
"organization": "Alliance for Open Media",
"groups": [
{
"name": "Storage and Transport Formats Working Group",
"url": …
```

Add the AVIF specification

---

specs.json

Detected when trying to use autolinks in network-error-logging as a result of https://github.com/w3c/strudy/pull/484
It wasn't automatically detected since it's "hidden" in the general Reporting API repo.
This adds the following JSON:
```json
{
"url": "https://w3c.github.io/reporting/network-reporting.html",
"shortname": "network-reporting",
"series": {
"shortname": "network-reporting",
"currentSpecification": "network-reporting",
"title": "Network Reporting API",
"shortTitle": "Network Reporting API",
"nightlyUrl": "https://w3c.github.io/reporting/network-reporting.html"
},
"nightly": {
"url": "https://w3c.github.io/reporting/network-reporting.html",
"status": "Editor's Draft",
"sourcePath": "network-reporting.bs",
"repository": …
```

Add Network Reporting API

---

test/index.js

The test expected all IETF entries to have an rfc-editor URL. That's not the case for IETF specs that have not yet been published as RFC. The test now simply ignores all specs associated with IETF to avoid returning false positives.

Relax test on repository for IETF specs

---

README.md
test/index.js

This adds a "Spec identifiers" section to the README to explain that there are no fully stable identifiers in browser-specs, but that the `shortname` and `formerNames` properties may be used to track a spec over time if needed.

[README] Describe spec ids and algo to track a spec over time

---

.github/workflows/build.yml
.github/workflows/check-base-url.yml
.github/workflows/lint.yml
.github/workflows/monitor-specs.yml
.github/workflows/release-package.yml
.github/workflows/report-new-specs.yml
.github/workflows/request-pr-review.yml

Some dependency updates seem to require Node.js v20. Switching all jobs for consistency.

Switch jobs to use Node.js v20

---

src/build-index.js

GitHub did not like the switch to Node.js v20 in jobs. Build fails at the determine filename step, without much info on top of a "fetch failed". This update forces throttling on the fetch requests in the hope that this can improve things.
It also logs specs being processed to provide more clues about what the problem might be.

Throttle filename check

---

README.md
schema/definitions.json
specs.json
src/compute-repository.js
src/compute-shortname.js
src/fetch-groups.js
src/fetch-info.js
test/compute-repository.js
test/compute-shortname.js
test/fetch-groups.js
test/fetch-info.js

The code now recognizes IETF draft documents that have a `datatracker.ietf.org` URL:
- It associates them with the IETF organization
- It can compute a useful shortname (that code can in theory return a truncated shortname because there is no direct way to validate that the Internet Draft name contains a group ID).
- It extracts the group's ID from the nightly URL (that code could further be improved to fetch the actual group name, right now the code only knows about the "HTTP" working group).
- It associates IETF documents from the HTTP WG to the right repository.
- It computes the better-looking nightly URL at `www.ietf.org` or at `httpwg.org` for HTTP WG documents.
This allows to simplify IETF data in `specs.json` a bit.
Note that the code still cannot process drafts that have been …

Automate processing of IETF (group) drafts

---

src/build-index.js

Before it runs a build step, the code loads the results of the previous step. If the file exists, it also loads the previous results of the current step, for use as fallback if some network issue occurs.
The loading was done using `require()`. The problem is that `require()` maintains a cache of loaded modules, so if the previous results of the current step existed, the code actually reused them for the *following* step as well.
This bug did not occur in production because the build job starts from scratch. In particular, it does not have previous results of build steps.

Fix build when previous build steps already exist

---

specs.json
src/fetch-info.js
test/fetch-info.js

Take 3 :)
PR #1135 actually had a couple of issues that made the code essentially useless because it only ran on a handful of IETF specs:
- the code favored info from Specref over info from IETF
- the code only really applied to drafts due to a buggy RegExp
Fixing these problems yielded a new issue: the assumption that HTTP WG specs are always available under `httpwg.org` turns out to be wrong. Also, there are other specs that are not published by the HTTP WG but that still have an `httpwg.org` version. The code now looks at the actual list of specs in the underlying GitHub repository: https://github.com/httpwg/httpwg.github.io.
As a result, the nightly URL of all IETF specs that have an `httpwg.org` version now targets that version, implementing the suggestion in #933 (see that issue for …

Fix and improve processing of IETF specs

---

test/index.js

This fixes #781, using a more generic set of rules. For `repository`, the test does not look at IETF and FIDO Alliance specs and also skips W3C specs that got published under www.w3.org and for which we don't have an Editor's Draft.
For `sourcePath`, the test simply skips over entries that don't have a `repository` property. There remains one exception to the rule but that seems fine.

[tests] More generic rules for repository/sourcePath tests

---

src/build-index.js
src/fetch-groups.js
src/fetch-info.js
test/fetch-groups.js
test/fetch-info.js

This fixes #1130 by turning the "discontinued" standing into a frozen state: when the last published version of web-specs says that the standing of a spec is "discontinued", the code directly reuses the information from that last published version for that spec.
There remained a couple of places in the build script that did not give priority to information specified in `specs.json`. This update also fixes that (and needs it!).
If a discontinued spec needs to be revived, the only way to do that will be to make the new standing explicit in `specs.json`.
Loading the last published version of web-specs could prove useful for #61 as well, but that's not part of this update.

Use last published information for discontinued specs

---

schema/definitions.json
specs.json
src/compute-repository.js
src/compute-shorttitle.js
src/determine-filename.js
src/fetch-groups.js
src/fetch-info.js
test/compute-shorttitle.js
test/determine-filename.js
test/fetch-groups.js
test/fetch-info.js

AVIF had already been added to the list. This adds remaining specs from the Alliance for Open Media related to AV1.
Logic also updated to find more info about these specs automatically.
Fixes #1088.
A couple of information points that are ok-ish but that could further be improved:
1. We only record the nightly URL for now, but the official final deliverable is the PDF version. The same is true for other specs, see PDF list at https://aomedia.org/av1-features/get-started/
2. The specs are extracted as "Editor's Draft" but the status should rather be "Final Deliverable" for some of them
<details><summary>Changes to index.json</summary>
```json
[
{
"url": "https://aomediacodec.github.io/afgs1-spec/",
"shortname": "afgs1-spec",
"series": {
"shortname": …
```

Add AOM specs

---

src/build-index.js
src/compute-alternate-urls.js
test/index.js

This help e.g. to detect outdated references in specs.
This will fail CI since it will need an updated index to pass (and am getting rate-limited when trying to do so locally)

Add alternate URLs for IETF RFCs

---

test/index.js

The datatracker URL does not have a trailing `/`.

Fix datatracker alternate URL test for IETF specs

---

src/data/ignore.json

Repository is for discussions only.
The [`w3c.json`](https://github.com/WICG/protected-auction-services-discussion/blob/main/w3c.json) mentions `cg-report` as repository type. That's not completely wrong (the repo could perhaps end up containing a CG report of the discussions), but perhaps worth updating to... [`others`](https://w3c.github.io/w3c.json.html#repo-type)?
Replaces #1154

Ignore WICG/protected-auction-services-discussion

---

src/data/monitor.json

The spec has not yet been published and would be considered to be the current spec in the series if we added it now.
Fixes #1160.

Monitor CSS Snapshot 2024

---

specs.json
src/data/ignore.json

The spec was being ignored (twice!) because it documents a deprecated API, and we didn't have a `discontinued` standing back in the days.
Needed by BCD, see request in #1162.
FWIW, the code misses the "Unofficial Draft" status of the nightly version because it expects this status to be "Editor's Draft" for all... well... Editor's Drafts linked to a /TR spec.
This will add:
```json
{
"url": "https://www.w3.org/TR/merchant-validation/",
"shortname": "merchant-validation",
"series": {
"shortname": "merchant-validation",
"currentSpecification": "merchant-validation",
"title": "The MerchantValidationEvent interface",
"shortTitle": "The MerchantValidationEvent interface",
"releaseUrl": "https://www.w3.org/TR/merchant-validation/",
"nightlyUrl": …
```

Add merchant-validation as discontinued spec

---

specs.json

Note WAI-ARIA 1.2 should remain the current specification for now.
Via #1173.

Add FPWD of WAI-ARIA 1.3

---

src/find-specs.js

This updates the find-specs script to also look for new WASM proposals in: https://github.com/WebAssembly/proposals/blob/main/README.md
Only phase 3+ proposals are being considered, in accordance with: https://github.com/w3c/browser-specs/issues/1181#issue-2109574914 ... which itself derives from:
https://github.com/web-platform-tests/interop/issues/589#issuecomment-1778823232
The script now filters out specs that cannot be fetched (some WASM proposals at phase 3+ do not have a proper spec).
Fixes #529.
The update will make the script report the following WASM proposals that are not yet in browser-specs:
- https://webassembly.github.io/branch-hinting/core/bikeshed/ from [WebAssembly/branch-hinting](https://github.com/WebAssembly/branch-hinting)
- …

Look for new WASM proposal specs at phase 3+

---

specs.json
src/find-specs.js

The list only contained Level 1 of WASM Core (see #1059). This adds Level 2. In practice, crawling will work fine for the Editor's Draft but Reffy will basically not extract anything from the /TR version of the spec because it does not follow usual patterns. That seems fine enough for now.
This update also introduces missing WASM proposals as forks of the WASM Core or WASM JavaScript API specification. Most of the time, the title needs to be created because the actual specification remains that of the base spec.
One difficulty is that the WebAssembly group approaches extensions proposals as generic WASM extensions, and not necessarily as WASM *Core* extensions or WASM *JS API* extensions, whereas we need to make a choice to set the `forkOf` property. Things look good for this batch of …

Add WASM Core 2 spec and phase 3+ WASM proposals

---

specs.json

The list documents the WASM threads proposal as an extension to WASM Core. The proposal also updates the WASM JS API:
https://github.com/WebAssembly/threads/blob/main/proposals/threads/Overview.md#javascript-api-changes
... and BCD needs to link to that spec, see:
https://github.com/mdn/browser-compat-data/blob/019005fc03eecb34e557183420a2f5482ebf9293/test/linter/test-spec-urls.ts#L28

Add WASM Threads proposal to update the JS API

---

specs.json

That was missed in the update that changed their shortname. This affected Specref, see: https://github.com/tobie/specref/pull/777
Also see #1195 for detecting the problem before a new index gets released.

Add formerNames properties to css-viewport-1 and WASM GC proposal

---

packages/browser-specs/README.md
packages/browser-specs/package.json
packages/web-specs/README.md
packages/web-specs/package.json

Both packages needed a major bump due to the possibility to now have specs without a `nightly` property. Package readmes now contain a short text to clarify breaking changes between major versions. To be completed over time as new major versions get released.

Bump major versions, document breaking change in package READMEs

---

.github/workflows/build.yml
.github/workflows/check-base-url.yml
.github/workflows/lint.yml
.github/workflows/monitor-specs.yml
.github/workflows/release-package.yml
.github/workflows/report-new-specs.yml
.github/workflows/request-pr-review.yml

as requested by github https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Upgrade github actions

---

test/fetch-info.js

Previous IETF draft used in the test was published as an RFC, and is no longer suitable for the test.
More generally speaking, we cannot expect these tests to remain completely stable over time unless we start mocking the response from the server... but then it's also good to check that the response we get from the server is as expected. In the meantime, I propose to consider that these tests are stable enough!

Adjust test on IETF draft nightly URL extraction

---

specs.json

The draft was moved to another repository. Previous URL returns a 404.

Update nightly URL of CHIPS spec

---

src/check-base-url.js

The CHIPS spec was already listed as an exception for which the mismatch is fine, but the URL needed to be adjusted following its transition to another repository.
Closes #1229.

Adjust check base URL script for CHIPS spec

---

schema/definitions.json
specs.json
src/determine-filename.js

This adds the GIF and JPEG specifications to the list, as requested in #1089.
For GIF, the most canonical URL is the specification published under `w3.org`, consistent with Specref and Wikipedia.
The notion of group does not mean much for the GIF spec. Also, the link to the CompuServe website seems a bit wrong, but a URL is needed...
For JPEG, the usual reference is to the interchange format (JFIF). A PDF version of the 1992 spec exists under `w3.org` at: https://www.w3.org/Graphics/JPEG/jfif3.pdf
That is the spec that Specref returns for JPEG. That said, JPEG is published and maintained by ISO/IEC under the name `iso10918-5`: https://www.iso.org/standard/54989.html
That spec (and name) is used in the list instead of the PDF version because it provides a more official entry point. If we …

Add GIF and JPEG (JFIF) specs

---

specs.json
src/determine-testpath.js
src/parse-spec-url.js

This adds 2 additional specifications developed by the Khronos Group, as requested in #1089, and adjusts the code that was a bit too specific to WebGL specs and extensions accordingly.
The notion of "Working Group" within the Khronos Group appears somewhat informal, but the terminology is used in the page that lists Working Group officers at least: https://www.khronos.org/about/working-group-officers/
Issue #1089 mentions GLSL, and not OpenGL **ES** Shading Language, but the latter is what WebGL uses, and so should be what browsers implement. The name `ESSL` is the official name for the ES variant, see: https://github.com/KhronosGroup/GLSL
That repository only contains extensions and the issue tracker for the GLSL and ESSL specifications, but not the actual specifications. I did not set …

Add OpenGL ES Shading Language and glTF 2.0

---

test/index.js

New Khronos Group specs do not have a repository. The test now stops looking at Khronos Group specs. That's a bit loose since all WebGL specs do link to a repository, but that test is not meant to be too precise either.

Add Khronos Group specs to the list of exceptions for repository test

---

src/data/monitor.json

The spec is an unofficial proposal draft for now. Closes #1242.

Monitor HTML Ruby Markup Extensions spec

---

src/data/monitor.json

Still early draft, with "no active development" according to Chrome Status.
Closes #1252.

Monitor Web Audio Playout

---

src/build-diff.js

So far, the build-diff tool only generated specs that effectively changed in `specs.json`. With this change, it now also re-generate the entries for the specs that are in the same series, and report possible changes to these specs in a new `seriesUpdate` property.
The change also switches to active forms for the property names: `add`, `update` and `delete` (instead of `added`, `updated`, `deleted`), because the changes to `index.json` are typically not yet done.
This change gets us closer to a mode where we can pre-compute the `index.json` that a pull request would trigger and run tests on them.
Still missing: forks. If changes add a `forkOf` property, include a rename of a spec that has a `forkOf` property, or delete a fork, the upstream spec entry needs to be re-generated as well. The …

Also re-generate specs in the same series when building diff

---

src/build-diff.js

This update makes the `src/build-diff.js` script accept the canonical URL of a spec as parameter, and build the updates to `index.json` that this URL would trigger if it were added to `specs.json` (or if it would replace the corresponding entry in `specs.json`).
The script still accepts commit references, although the syntax was slightly updated to get back to one parameter and better align with `git diff`, from `node src/build-diff HEAD HEAD~2` to `node src/build-diff HEAD..HEAD~2`.
The script is now also available as a module and the exported function also accepts additional spec properties on top of the URL. That is not yet used but will be useful for later.
Next step is to create a more proper CLI that makes use of the module, can also run tests on the updates, and propose a …

Update build-diff script to also accept a URL

---

src/cli.js

Failed test titles were reported as "${test.title}", which wasn't super useful.

Fix string replacement hiccup in CLI

---

.github/workflows/submit-suggested-spec.yml
src/cli.js

I was sort of hoping that the `gh` CLI command would take care of pushing the local commit automatically to GitHub without having to specify the name of a remote. That does not seem to be possible...
This update adds a `git push` command, which unfortunately hardcodes the `origin` remote name in the CLI.

Submission jobs: push changes before running gh command

---

src/cli.js

Entries in the monitor and ignore list sometimes use casing that is different from what we end up with in the `index.json` file (e.g. , `WICG` vs. `wicg`). This update makes the comparison case-insensitive.
Prompted by #1274, which should trigger removal of the repo entry from the monitor list.

[CLI] Make monitor/ignore comparison case insensitive

---

src/data/ignore.json
src/data/monitor.json
src/find-specs.js
test/data.js

This addresses #238, adding checks that there are no entries in the monitor or ignore list that are already in the main list.
This also adjusts the find-specs script to:
1. skip fragments in repository homepage URLs (`WICG/close-watcher` does that)
2. also look at spec pages to find URLs, to avoid reporting a spec that is already in the list (`WICG/close-watcher` also does that as it now points to an HTML page)
3. compare strings in a case insensitive way, as we sometimes end up with different casing for repo names and URLs.
A couple of entries needed to be removed from the monitor/ignore list as a result ;)

Test monitor/ignore entries against main list, adjust find-specs

---

src/cli.js

Close #1282 by adding a "close" statement in the commit message that references the parent issue.

[CLI] Add "close" to commit message to close issue automatically

---

.github/workflows/report-new-specs.yml
.github/workflows/submit-suggested-spec.yml
package.json
src/cli.js
src/find-specs.js

Two related updates:
- Add option to tell the bot to monitor/ignore a spec (that would close #1287)
- Make find-specs create one issue per spec (that would close #1288)
See individual commit messages for details, in particular for the monitoring of repos without published content feature, which I'm proposing to drop, unless there's a reason to keep it that I overlooked.

Report new spec in issues, add command to monitor/ignore a spec

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/release-package.yml
.github/workflows/request-pr-review.yml
src/build-index.js
src/prepare-release.js
src/release-package.js
src/request-pr-review.js
test/fetch-groups.js

Via #1307.
The `gh` command that we now use in some of our jobs look for a `GITHUB_TOKEN` environment variable to find the authentication token, while our code rather used `GH_TOKEN`.
The job that checks a suggested spec uses both our code and the `gh` command. To avoid having to set the token to two different environment variables, this updates rather aligns everything to `GITHUB_TOKEN`.

Look for auth token in GITHUB_TOKEN (was GH_TOKEN)

---

specs.json
src/build-index.js

The build logic expects that, for CSS specs, when a /TR/ spec that has some level links to a nightly draft without level, then it should add the level back. That no longer works for CSS Viewport, as css-viewport-1 no longer exists on the draft CSS server.
This update forces the nightly URL of the CSS Viewport to be without level (and fixes the build code to actually use that URL when it is specified).

Make nightly URL of CSS Viewport explicit

---

specs.json
src/determine-filename.js
src/fetch-info.js

The updates fix a couple of test failures that currently prevent builds, and should provide more info about the remaining one (lack of `filename`).

Handle FPWD for nightly, fix orientation-event series info, log filename responses

---

src/build-index.js

If the code cannot determine the filename of a spec, it reuses the previously known filename... at least in theory. In practice, the code was not loading the previous index but the intermediary build step, which does not exist when the build is run as part of a job.
This makes the code load the previous `index.json` file. Filename is the only place where that previous index is used.
That won't fix #1333, but the build might actually succeed with this change.

Use actual previous index to determine filename

---

specs.json

The WICG spec moved to actual standardization with two parts:
1. The IDL part was moved to HTML in https://github.com/whatwg/html/pull/8467
2. The CSS part is to be integrated in Selectors, see https://github.com/w3c/csswg-drafts/issues/4805
This flags the spec as obsoleted by these two specs, using `selectors-4` for the CSS part. The CSS WG resolution mentions Selectors 5 but it does not exist yet. Alternatively, we could keep this PR open until the CSS part gets specified, or not mention `selectors-4` at all for now. Not sure which is better. Merging earlier rather than later would help with Webref (to remove the duplicate IDL).

Flag custom-state-pseudo-class as discontinued

---

schema/definitions.json
schema/index.json
schema/specs.json
specs.json
src/determine-filename.js

W3C servers have started to become stricter about rate limits, making build jobs fail with "429 Too Many Requests" responses received. In practice, as reported in #1333, all /TR specs have an "Overview.html" but two. This update hardcodes the rule: "All /TR URLs have an Overview.html filename" and adds the two exceptions to the rule to specs.json.
Note the `release` property was not yet allowed in `specs.json` (because we never had a need for it). The schemas needed to be updated as a result. To avoid requiring properties under `release` that are useless in specs.json, the definition was split into two: one for specs.json without constraint, and one for index.json that reuses the first one but also adds required constraints.

Force filename to Overview.html for W3C /TR URLs

---

index.json

The build code gets lost with the `custom-state-pseudo-class` entry because the URL now redirects to a section of the HTML spec. Goal is to make the entry discontinued. Once that is done, the build code should reuse the info from index.json directly (the discontinued state is a frozen state).
This update forces the standing of the entry to discontinued, reusing previous info for other entry properties. This should fix the issue at hand and allow build to resume.
The other updates are triggered by recent changes to `specs.json` that have not yet been integrated in `index.json` because the build could not succeed. No manual changes were made to these updates.

Force update of index.json, adjusting discontinued entry

---

src/extract-pages.js
src/fetch-info.js
src/load-spec.js

Build currently fails with a timeout when it tries to load the ED of CSS2 to extract the list of pages from the table of contents (the ED is not a multipage spec per se, but the /TR version is, and the "multipage" flag applies to both).
That timeout is due to images taking a long time to load on the CSS drafts server right now for some reason. Puppeteer surrenders after 30s of trying to fetch the images. That is not specific to the context under which the build is run: I get the same timeout when I run things locally.
As a workaround, this update reuses in extract-pages the same load logic as the one used in fetch-info, which itself is a copy-and-paste from the logic used in Reffy to crawl the specs. That logic notably avoids loading resources identified as images, which solves the …

Optimize spec page loading everywhere

---

CONTRIBUTING.md
schema/specs.json
specs.json
src/build-index.js
src/lint.js
test/lint.js

The job still fails to load the ED of the CSS 2.2 spec to extract the list of pages, even with optimized loading (added in last commit). Something's rotten in the State of Network.
In practice, build does not *need* to load the ED of the CSS 2.2 spec. It just does it because the spec is identified as multipage due to the /TR version. To avoid unnecessary spec loads, this update converts the `multipage` flag from a boolean to a string with 3 possible values: "all", "release", "nightly". The extraction of the list of pages is now only done on the version targeted by the `multipage` property.
The update also serializes the extraction of pages to avoid sending too many requests at once. There are only a handful of specs for which we need to look for pages, serialization should not make build …

Make `multipage` flag specifically target release and/or nightly

---

src/load-spec.js

Resources from test.csswg.org are used to add test annotations to a CSS spec. We don't need that information, and these resources seem to contribute to network timeouts. This update adds them to the blocklist of resources that get intercepted when the spec is loaded in Puppeteer.
Note: I'm not really expecting that change to solve the timeout issue on SVG2, but hopefully that can help...

Don't load resources from test.csswg.org

---

src/build-index.js
src/determine-filename.js

This update restricts the actual determination of filenames to new specs, to avoid network requests. When network requests need to be sent, they are now sent sequentially, with a 1s delay between requests. There should be a handful of specs for which network requests are needed at most.

Always reuse previously determined filenames

---

.github/workflows/build.yml
package.json

The build is failing because it is running the full test suite which makes HTTP requests that fail; while that is probably worth addressing on its own, it is not necessary to test the code when it is only the data we're updating, which this PR enables.

Limit test on builds to data

---

src/fetch-info.js
src/load-spec.js
src/throttled-queue.js

This imports the adjustments made to the throttling logic in Reffy. In the end, it seems useful to adopt the same strategy regarding sleeping between requests: 2s for CSS server, 1s for www.w3.org, and 100ms for other origins.
This raises the question of whether that logic should rather be integrated into throttled-queue.js if we use the same logic everywhere. Oh well ;)
Refresh also skips CSS resources as done in Reffy.

Refresh throttling logic (based on code used in Reffy)

---

specs.json
test/index.js

The css-overflow-5 spec was added last week as a full spec, but css-overflow-4 is a delta spec. On top of being incorrect because level 5 is also a delta spec, the succession full > delta > full confuses Reffy, who considers that level 5 is the "latest version" it should report extracts for, instead of level 3: it ends up with creating a `css/css-overflow.json` extract for level 5, `css/css-overflow-4.json` for level 4, and no extract for level 3.
This update makes css-overflow-5 a delta spec and adds a test to guarantee that a delta spec can never be followed by a full spec in its series.

Make css-overflow-5 a delta spec, add related test

---

specs.json

The source of the spec was moved to the main ARIA GitHub repository. The Editor's Draft is still being served from the previous repository though, meaning the URL of the Editor's Draft remains unchanged.

Update repository for core-aam

---

specs.json
src/compute-repository.js
src/parse-spec-url.js
test/compute-repository.js

[Now I know why I was confused with accname and core-aam. Both had already moved! ;)]
More specs have moved in the past few hours. Migration of the html-aam spec is still pending but there's an open PR for that, and the spec already exists under the ARIA mono-repository.
This update hardcodes the rule "all specs whose nightly URL end with -aam or -aria are in the w3c/aria repository". Except for html-aria, which is developed by the WebApps WG in a different group. The logic now also finds the source file on its own in that repository.
This avoids having to add `repository` and `sourcePath` in `specs.json` for all these specs. The `accname` spec remains an exception to the rule because it does not end with `-aam` or `-aria`.

Deal with ARIA exodus

---

src/find-specs.js

The script was expecting tables to follow their headings at the same level in the HTML, but GitHub now wraps tables in `<markdown-accessibility-table>` web components, and headings in a `<div>`.

Fix parsing of github.com pages in find-specs script

---

specs.json

Missed during previous update.
Arguably, the continuity exists through the series shortname, but the guarantee that we make is that any shortname that used to appear will either appear as a shortname or in a `formerNames` property.

Add `encrypted-media` as former name for `encrypted-media-2`

---

specs.json

This adds the registries and notes recently published by the Media WG.
Tested with `npx browser-specs build`. Note the need to set the series shortname for `eme-stream-mp4` otherwise the code would strip the `4`.
This revealed a couple of places where the W3C API returned incorrect information. Now fixed.
I also took the opportunity to drop series titles that had been set because the W3C API also returned incorrect information, and that are no longer needed.

Add recently published media registries and notes

---

specs.json
src/build-diff.js

Per #1427.
This also fixes the build-diff logic which duplicated the entry in the new index it creates for testing purpose, because the check on whether specs are effectively distinct did not take the spec's shortname into account.

Update URL of Source Map

---

specs.json

We still had the Editor's Draft... whose URL changed as well.

Update URL of PNG specification

---

specs.json

The Web Payment WG is going back to a level-less shortname for payment-request.
/cc @ianbjacobs

payment-request is switching back to a level-less shortname

---

test/specs.js

When the tests are run as part of a "build" command run from the CLI, the tests on `specs.json` and `index.json` do not actually run on the files but on copies amended with would-be updates. The path to the copy is read in an environment variable. The `specs.json` tests were run against the `index.json` copy, likely due to a hasty copy-and-paste in a previous update. That explains the weird test failures reported in the latest spec suggestion issues.

Fix specs.json tests when run from the "build" CLI command

---

src/find-specs.js

The link to one of the current TC39 stage 3 proposals contains a trailing `#README` fragment.
Via #1442.

[find-specs] Drop fragments from extracted URLs

---

src/check-base-url.js

Prevented the script from running.

[Check base URL] Fix JSON import

---

specs.json

Spec was published as a First Public Working Draft.
Fixes #1478 (manual because the logic does not properly handle the case when a spec transitions to /TR yet)

Add CSS Easing Level 2

---

specs.json

First Public Working Draft published under the `fedcm-1` shortname.
Replaces #1486. Changes tested locally.

Update URL of FedCM and record former shortname

---

specs.json
src/build-diff.js

The CSS Values 5 spec was publised as First Public Working Draft last week.
There are 3 specs in the series (Levels 3, 4 and 5). The diff build script tried to build the other specs in the series twice, one time for the "add" operation and one time for the "delete" operation, which made tests fail. The code now adds specs in the same series only once.
Build test locally, no errors reported.
Fixes #1489 (need to be done manually because automation script cannot delete the previous URL on its own).

Update URL of css-values-5, fix duplicates in diff build

---

specs.json

The spec remains an unofficial individual draft in the PAT CG for now, but:
1. It ships in Chromium, where it's enabled by default. So could be useful for the MDN BCD collector.
2. The Shared Storage API, which is in good standing, has started to normatively reference IDL terms and concepts from the Private Aggregation API. If standings of both specs are different, we end up with IDL inconsistency in Webref's curated data.

Private Aggregation API: switch to good standing

---

specs.json

Our build code is smart: it detects that the spec says it is an unofficial proposal draft and determines that standing should be "pending" as a result.
This forces the standing to "good" since that's the intent of previous commit.

Force Private Aggregation API standing to good

---

specs.json

The digital-credentials repo was added to the monitor list back in January (#1174). The digital-identities spec was added shortly afterwards (#1204), but was using a different repository at the time.
Then digital-identities became digital-credentials, but we missed that. Instead we recently reviewed the list of monitored specs and decided to add digital-credentials (#1477).
That means we have twice the same spec in the list. This update drops the digital-identities entry and adds the name as a former name of digital-credentials, since that's the name under which the spec is now progressing.

Drop digital-identities entry, now digital-credentials

---

src/cli.js

The monitor/ignore bot commands expected to receive as comment ID the same ID as the one returned by the `gh` CLI. That would have been way too easy! The comment ID in a workflow is an integer while the ID returned by the `gh` CLI is a string (probably an encoding of the number?). The code now computes the URL of the comment from the comment ID and uses that instead to find the comment in the list returned by `gh`.
The update also fixes a bug in the regular expression used to extract the actual comment (extracted string included the "because" prefix).
Closes #1496.

Fix monitor/ignore bot commands

---

specs.json

The draft used to be without a level but gained one recently, changing the actual shortname of the spec:
https://github.com/w3c/csswg-drafts/commit/2329ab24e2602ca41a6e9d127174ca251d9e03e1
(Build failed because it could no longer find the path to the source in the GitHub repository)

Add level to canonical URL of css-color-hdr

---

specs.json

Fixes #1544. The spec moved to the HTTP Working Group in IETF.
Note the new URL will produce the same shortname as before.
This will produce the following changes in `index.json`:
```json
{
"url": "https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-no-vary-search",
"shortname": "no-vary-search",
"series": {
"shortname": "no-vary-search",
"currentSpecification": "no-vary-search",
"title": "No-Vary-Search",
"shortTitle": "No-Vary-Search",
"nightlyUrl": "https://httpwg.org/http-extensions/draft-ietf-httpbis-no-vary-search.html"
},
"organization": "IETF",
"groups": [
{
"name": "HTTP Working Group",
"url": "https://datatracker.ietf.org/wg/httpbis/"
}
],
"nightly": {
"url": "https://httpwg.org/http-extensions/draft-ietf-httpbis-no-vary-search.html",
"status": …
```

Update URL of no-vary-search draft

---

specs.json

The API used to have a "pending" standing because its status was "Unofficial Draft Proposal". That seems good (and the proposal has a negative standard position from Mozilla). The status of the spec changed to "Draft Community Group Report" recently, which was enough to make our code switch the standing to "good".
I missed that change when I reviewed the diff of web-specs and released a version of web-specs with that updated standing. This means Webref now tries to curate the IDL defined in the spec, and fails because the IDL references the `[IsolatedContext]` extended attribute that currently exists as a monkey patch in the Isolated Contexts spec.
We may of course update Strudy to accept `[IsolatedContext]` but I'm thinking that the right standing for the spec remains "pending" for now. …

Flag Direct Sockets API as pending

---

specs.json
src/fetch-info.js
test/fetch-info.js

For some reason, the code assumed that the fetch API would not follow permanent redirects.
The fetch API follows redirects by default and that's a good thing as requests on the `/specifications/[shortname]/versions/latest` API endpoint typically return a 302 to the actual version that is the current latest version.
This update rather relies on the `redirected` flag to detect redirects and checks the final URL to see whether the W3C API knows the spec under a different shortname. It throws when that happens, as before.
Build would typically fail on `webaudio` since it is now known as `webaudio-1.0` in the W3C API. This updates the shortname accordingly.

Fix detection of shortname change, update shortname of webaudio

---

specs.json

The WebP draft was published as [RFC9649](https://www.rfc-editor.org/rfc/rfc9649) (build currently fails because of that, as code detects the new URL).
The `webp` shortname feels more appealing but we use `rfcxxxx` shortnames for all other IETF RFCs, so moving `webp` to the list of former names.

Replace WebP draft with newly published RFC

---

specs.json

Need to be done explicitly until #1604 gets addressed.

Mark Open Screen Protocol as obsoleted by App and Network protocols

---

specs.json

Via https://github.com/w3c/process/issues/962
(depended on Specref being updated)

Update URLs of W3C Patent Policy and Process document

---

specs.json

Both specs were published as First Public Working Drafts. Fixes #1613, #1614.

Update URLs of css-overflow-5 and css-color-hdr-1

---

specs.json

Following publication as FPWD. Also, css-multicol-2 is no longer a delta spec.
Close #1621
Close #1622

Update URLs of css-display-4 and css-multicol-2

---

.github/workflows/build.yml
.github/workflows/check-suggested-spec.yml
.github/workflows/lint.yml
.github/workflows/report-new-specs.yml
.github/workflows/submit-suggested-spec.yml

Needed now that GitHub Actions switched to Ubuntu 24.

Disable AppArmor in jobs that use Puppeteer

---

src/fetch-info.js

This provides a more generic solution to #1606.
Browser-specs has become the main source for Specref for WICG specs and W3C Editor's Drafts. The code no longer attempts to fetch info for these specs from Specref as a result.
Tested locally, this will adjust a handful of spec titles (to match the actual spec title, which seems good)... and the URL of element-timing! Interestingly, it will also adjust a few WICG entries for which the spec says the status is "Unofficial Draft", which will also switch the standing of these specs to "pending". That seems good as well although we may want to review these changes before we release a new version. I propose to do that separately in any case. Specs in that category include: Web Share Target API, preferCurrentTab, the CSS Parser API.
Note: Specref …

Stop fetching info from Specref for WICG specs and W3C ED

---

specs.json

See discussion in:
https://github.com/w3c/browser-specs/pull/1628#issuecomment-2586337351
Specs used to come with a "good" standing in browser-specs because data came from Specref. The specs themselves continue to say they are unofficial drafts, and so build code now considers that these specs should have a "pending" standing.
That standing seems correct, but WPT already has actual tests for the CSS Parser API (on top of IDL tests), and already integrated the preferCurrentTab IDL as well (just a partial dictionary definition in practice). This update forces the standing to "good" for continuity.

Force a good standing for CSS Parser API and preferCurrentTab

---

specs.json

The spec is documented on MDN already, so the switch to "pending" is not fantastic for BCD and web-features. See context in: https://github.com/w3c/browser-specs/issues/1645
https://github.com/w3c/browser-specs/pull/1628#issuecomment-2589699597

Force a "good" standing for the Web Share Target API

---

specs.json
src/data/monitor.json

Close #1654, adding the suggested spec to the list.
This update would trigger the following changes in `index.json`:
<details><summary>Add spec (1)</summary>
```json
{
"url": "https://wicg.github.io/aom/spec/",
"shortname": "aom",
"series": {
"shortname": "aom",
"currentSpecification": "aom",
"title": "Accessibility Object Model",
"shortTitle": "Accessibility Object Model",
"nightlyUrl": "https://wicg.github.io/aom/spec/"
},
"groups": [
{
"name": "Web Platform Incubator Community Group",
"url": "https://www.w3.org/community/wicg/"
}
],
"nightly": {
"url": "https://wicg.github.io/aom/spec/",
"status": "Unofficial Proposal Draft",
"repository": "https://github.com/WICG/aom",
"sourcePath": "spec/index.html",
"filename": …
```

Add Accessibility Object Model

---

specs.json
src/fetch-info.js

Browser-specs still fetched info from Specref for a few W3C specs, notably the `css-backgrounds-4` draft and a few policy documents. Info is now fetched directly from the spec for these specs. This will make it possible to properly retire `csswg.json` in Specref.
The GIF spec, published under `https://www.w3.org` is treated as an exception to the rule, because its URL ends with `.txt`, signaling a spec published in plain text.
Note: Browser-specs still leverages Specref, mainly for WHATWG specs, a few TC39 and ISO specs, and a couple of CG specs that use their own GitHub org.

Don't fetch info from Specref for CSS and www.w3.org specs.

---

test/index.js

The "Borders" part is now the topic of a separate spec, series title is still that of the current specification, meaning level 3.
The update also drops the exception for `css-images-4`, no longer needed.

[Tests] Add exception for series title of css-backgrounds-4

---

specs.json
test/index.js

The update preserves the former shortname `speech-api` for now, matching the
`shortname` metadata currently present in the spec.
Fixes https://github.com/w3c/browser-specs/issues/1639

Update URL of Web Speech API

---

schema/definitions.json
src/fetch-groups.js
src/fetch-info.js
src/fetch-json.js
test/fetch-info.js

Build code used to rely on Specref to get the title of WHATWG specifications. This update makes it fetch info for WHATWG specs from the WHATWG database directly. To save one request, the code leverages the workstreams database, also used by fetch-groups, instead of the biblio file.
On top of adding a new `whatwg` value to the `"source"` field, this update will also fix the titles of the WHATWG specs: they end with "Standard" in Specref but, while that matches the `<title>` tag, the actual spec title in the `<h1>` and the title in the WHATWG database don't end with "Standard". *#docallmeDOM*
The update turns the `fetchJSON` function into a utility function. This is going to save a few requests (not that many!) that are common between fetch-info and fetch-groups. Specific functions in …

Retrieve WHATWG spec titles from WHATWG database

---

README.md
schema/definitions.json
src/fetch-info.js
test/fetch-info.js

This completely drops the logic that used to fetch spec info from Specref. Motivation for the change is to avoid having a circular dependency between browser-specs and Specref that makes it cumbersome to make some updates.
In practice, there remained only 6 specs for which browser-specs was leveraging Specref: 3 from ISO, 2 from TC39 and the Web Bluetooth API.
One consequence is that the title of the TC39 specs will change because the actual specs include a registered mark and the year, which are now captured, leading to "ECMAScript® 2025 Language Specification". Maybe not ideal, but then that's per spec...
README and comments updated in the code to remove mentions of Specref.

Stop fetching spec info from Specref

---

src/build-index.js
src/compute-shorttitle.js
test/compute-shorttitle.js

Via #1676. The "Privacy-Preserving Attribution" spec separates the main title and the level with a `:`, which wasn't handled as part of the logic used to shorten the title.

Drop ":" before "Level" to compute short and series titles

---

specs.json
test/fetch-info.js

The W3C API was updated to make `CSS2` the actual spec and to have `CSS21` redirect to `CSS2`. This follows from discussions with @fantasai, @tabatkins and @deniak to clarify that revision 1 and revision 2 of CSS Level 2 should be viewed as just CSS Level 2.
This update folds the CSS 2.1 and CSS 2.2 entries into one CSS 2 entry accordingly:
- Shortname is `CSS2`. That used to be the shortname we had for CSS 2.1, until we updated it to `CSS21` to be consistent with the W3C API a few months ago (through #1560)
- Published version is at https://www.w3.org/TR/CSS2/
- Editor's Draft is at https://drafts.csswg.org/css2/
A side benefit is that there will no longer be duplicated definitions in Webref for CSS 2.1 and CSS 2.2. That should remove one of the de-duplication rules.
Note the W3C API …

Fold CSS 2.1 and CSS 2.2 into a CSS 2 entry

---

src/data/ignore.json

CSS 2.1 and CSS 2.2 remain separated from a /TR perspective, but should end up being folded into a single CSS 2 entry, with a `CSS2` shortname. We already force this view in browser-specs (done in #1696), to avoid introducing duplicated definitions.

Ignore CSS 2.2

---

src/check-base-url.js

CSS Level 2 revisions are squashed into a single CSS2 entry on purpose: the existence of different shortnames is a historical artefact, goal is to have only one CSS2 shortname from now on.
Close #1708

[Check base URL] Add CSS2 as an exception to the rule

---

src/build-diff.js

When diff building a spec, other specs in the same series need to be re-built as well. The code correctly picked up the other specs in the same series but forgot that entries in `specs.json` may either be a string or an object with a `url` property when it removed duplicates, leading to an incomplete list in the end.
Fixes #1713

Fix lookup of series for diff building

---

specs.json

Via https://github.com/w3c/webref/issues/1496.
The W3C API still reports that the shortlink URL for CSS2 is https://www.w3.org/TR/CSS21/ whereas that URL now redirects to https://www.w3.org/TR/CSS2/
Will work with @deniak to update the URL in the W3C API. In the meantime, this update forces the release URL to https://www.w3.org/TR/CSS2/.

Force release URL of CSS2 spec to /TR/CSS2/

---

specs.json

Now published with an official spec ID. The former name is retained in the `formerNames` property.
Note the `-` in the shortname for consistency with the `ecma-402` entry.
The "Editor's Draft" status is no longer needed. It used to be needed because the spec claimed it was an unofficial draft.

Adjust URL and shortname of Source map spec

---

src/compute-series-urls.js
test/compute-series-urls.js

For CSS2, we create a "CSS" series in browser-specs different from the "css" series for CSS snapshots but the W3C API mixes both, and the URL https://www.w3.org/TR/CSS/ that would logically be computed as series URL for the CSS series actually returns a CSS Snapshot. The update makes the code use the CSS2 spec URLs instead.
An alternative would be to create a "CSS2" series instead, but that's less aligned with the current data in the W3C API.

Handle CSS2 series URLs as an exception to the rule

---

specs.json

The W3C API now returns the /TR/CSS2/ URL for CSS2, the URL no longer needs to be specified in `specs.json`.
Note: this is the expected follow-up to #1726

Drop release URL for CSS2 (URL was fixed in the W3C API)

---

src/compute-repository.js
test/index.js

The specs belong to a common repository that uses a slightly different pattern that wasn't yet supported. Also, as for other specs following the `fooXY-bar` pattern, the series title does not completely look like the spec's title. The test now considers the `fooXY-bar` case as an exception to the rule.

Further extend support for `shacl12-*` specs

---

src/build-diff.js
src/cli.js
src/find-specs.js

When it finds a candidate /TR URL for a spec that was already in the list through its ED URL, the find-specs script now also adds a link to the ED in the rationale section of the issue.
When it finds a candidate /TR URL for a spec for which there is a pending issue for the ED URL, the find-specs script now creates a new issue for the /TR URL that links to the ED URL issue in the rationale section. The script also closes the ED URL issue with a "Superseded by #xxxx" comment.
The build logic leverages the ED link to also propose the deletion of the ED entry from the list at the same time as the /TR URL is added.
The update also introduces improvements to the comparison logic in the find-specs script, and skips the check on open issues before creating a new one (that's no longer needed …

Support ED to FPWD transition

---

specs.json

The `content-editable` spec used to be known as `contentEditable`.
Not sure yet why the test on shortname continuity did not capture that...

Add former name of content-editable

---

specs.json

There used to be one Recommendation for Subresource Integrity, whose shortname was `SRI`. A new level 2 was published as First Public Working Draft today. Shortnames got updated accordingly: `sri-2` for the new level, and `sri-1` for the previous Recommendation, and `SRI` now returns that new level. Our build code detects the redirection and does not like it.
This updates the URL in the list to use `sri-2` (recording `SRI` as a former name). We could keep an entry for `sri-1` but we usually only do that when the current spec is not the latest level.

Update URL of Subresource Integrity

---

specs.json

The TC39 committee has updated the source of ECMA-426 to source-map-rev3.md.

Update ECMA-426 source reference

---

specs.json

Same story as with Subresource Integrity (#1805), Level 2 of the Web Crypto API was published as FPWD yesterday, and the `WebCryptoAPI` shortname is now no longer a true spec shortname.
This updates the entry to use `webcrypto-2` as shortname and records the former shortname.

Update URL of WebCryptoAPI

---

src/fetch-groups.js
src/fetch-json.js

The validate-repos project collects all known `w3c.json` file, and contains
the information we need to map repo names to groups for a good chunk of specs.
This still does not work well for /TR specs because we guess the name of the
repository from the spec's shortname, but that's still better than what we used
to have!
Also, the `fetchJSON` function was only applying loose throttling, but
https://raw.githubusercontent.com/ is starting to return 429 responses after a
while. Documentation does not say much, but it would seem the limit is around
~5000 requests per hour. This update makes the function sleep 1000ms in
between requests to a given origin.

Leverage validate-repos and throttle requests on w3c.json files

---

src/monitor-specs.js

The monitor job correctly determines the set of issues that need reviewing, but then incorrectly looped over the entire set of open issues when updating GitHub...

Monitoring: loop through the right set of issues

---

specs.json

The spec moved to the FedID WG.
Fix #1848

Update URL of digital-credentials spec

---

src/compute-categories.js

The group used to be known as the "RDF-star" working group. New name needed to be added to the list of non-browser groups to avoid categorizing the group's deliverables as "browser" specs.
Note: the list still contains the previous name in case some data remains that still references that name.
Via https://github.com/w3c/browser-specs/pull/1828#pullrequestreview-2820568835

Add new RDF/SPARQL WG to list of "non-browser" groups

---

index.json
specs.json

... and integrated in Media Queries Level 5.
The previous URL now redirects to a section in Media Queries. This update also makes the update in `index.json` and rolls back the information there to the latest published info because build will otherwise update the title to "Media Queries".
(Note: once merged, a new package needs to be published right away, as we need a release with the "discontinued" status, otherwise the code will keep looking at the spec and update the entry with the *wrong* info).

Flag Web Preferences API as discontinued

---

test/index.js

Via #1860. The code gets lost because the spec title contains three level annotations: "Timed Text Markup Language 2 (TTML2) (2nd Edition)". The series title is "Timed Text Markup Language (TTML)", which is good.

Relax series title test for TTML2

---

schema/definitions.json

The Privacy Principles spec just got published as a W3C Statement. That's the first time we have an entry with that status in the list. The JSON schema needed to be adjusted accordingly.

Support "Statement" status

---

specs.json

The `ppa` draft was published as First Public Working Draft under a different shortname `privacy-preserving-attribution`.

Update URL and shortname of privacy-preserving-attribution

---

src/data/multispecs-repos.json

The repository contains the current ED of the SSN and SSN Extensions ontologies.

Add `w3c/sdw-ssn-sosa` to multi-spec repos list

---

test/fetch-groups.js

The W3C API returns a new URL. Previous URL redirects to that one too.

Adjust URL of ARIA WG page in test

---

src/build-index.js

I *almost* got it right yesterday ;)
Builds that do not fetch the ISO catalog use previous info. The code that associated previous info with the actual list of specs to process was only matching on the spec's *computed* shortname. That computed shortname is a temporary one for ISO specs, it gets changed right after that step when ISO specs get processed. Code now also matches on the spec's URL if match on shortname did not work.

Fix matching of ISO specs when attaching previous info

---

specs.json

Via https://github.com/web-platform-tests/wpt/pull/54005#issuecomment-3127534609
The spec's shortname will also change from `cookie-store` to `cookiestore`. Recording the former name in `formerNames`.

Update URL of Cookie Store API following move to WHATWG

---

test/index.js

Version 1.3 has a different title because it only contains a text profile. Adding it to the list of exceptions.

Skip series title test on ttml-imsc1.3

---

specs.json

Close #2066, adding also WCAG 2.2 because it is the current specification in the series. Note the need to override the series shortname for WCAG 2.2, as the series shortname is now lower-case, and the need to skip a couple of tests as WCAG 3.0 title is different, and as there is no obvious source file for the spec (it gets generated from a mix of files, the entry point is code, not content).
This update would trigger the following changes in `index.json`:
<details><summary>Add spec (2)</summary>
```json
{
"url": "https://www.w3.org/TR/WCAG22/",
"shortname": "WCAG22",
"series": {
"shortname": "wcag",
"currentSpecification": "WCAG22",
"title": "Web Content Accessibility Guidelines (WCAG)",
"shortTitle": "WCAG",
"releaseUrl": "https://www.w3.org/TR/wcag/", …
```

Add WCAG 2.2 (current spec) and WCAG 3.0

---

test/index.js

Forgot to include that update in PR #2094... As said there, the series title matches the title of the current specification (WCAG 2.2) but WCAG 3.0 introduces a new title.

Add WCAG 3.0 to list of exceptions for series title check

---

specs.json

The Editor's Draft now contains the previous level, and the Web IDL interfaces of Level 1 in particular. Curation in Webref fails accordingly.
Note: the /TR version hasn't been updated yet and is still to be viewed as a delta spec over Level 1. We don't have a way to capture "delta in /TR, non-delta in ED" though in the current data model though. This gives priority to the `nightly` status because that's the reference one for data.

Drop "delta" status for css-view-transitions-2

---

packages/web-specs/package.json
specs.json

The list already had v2.1. This adds latest version v2.2.
The shortname was `fido-v2.1` which seems too generic given that the FIDO Alliance publishes other specs that we might want to add in the future. Shortnames now have `ctap` to disambiguate.
Fixes #2122.

Add FIDO CTAP v2.2 and adjust shortnames of FIDO specs

---

src/compute-categories.js

The `vocab-ssn-ext` specification was last published in 2020 by the Spatial Data on the Web Interest Group. Code only knew about the more recent Spatio-temporal Data on the Web Working Group, and incorrectly categorized the spec as targeting browsers.

Add former SDW Interest Group to non-browser group list

---

specs.json

Draft IETF spec has now been published as an RFC. Close #2171.
This would add the following entry (no repository but there aren't any anymore as https://github.com/httpwg/http-extensions/ now merely contains the "previous" draft:
```json
{
"url": "https://www.rfc-editor.org/rfc/rfc9842",
"shortname": "rfc9842",
"series": {
"shortname": "rfc9842",
"currentSpecification": "rfc9842",
"title": "Compression Dictionary Transport",
"shortTitle": "Compression Dictionary Transport",
"nightlyUrl": "https://www.rfc-editor.org/rfc/rfc9842"
},
"formerNames": [
"compression-dictionary"
],
"organization": "IETF",
"groups": [
{
"name": "HTTP Working Group",
"url": "https://datatracker.ietf.org/wg/httpbis/"
}
],
"nightly": {
"url": "https://www.rfc-editor.org/rfc/rfc9842", …
```

Add RFC9842, replacing `compression-dictionary`
