w3c/browser-specs

LICENSE.md
=> Add open source license

src/build-index.js
=> Trap errors and fail properly when building index

specs.json
Added to the crawl list in:
https://github.com/tidoust/reffy/commit/933defb8db699ea62631b1ecdee3556afc358baf
=> Add Web Periodic Background Synchronization

specs.json
See discussion in https://github.com/tidoust/reffy/pull/282
=> Drop Box Tree API Level 1 from the list

specs.json
See #51. The spec has been officially retired.
=> Drop CSS TV Profile 1.0

specs.json
See https://github.com/WICG/scroll-to-text-fragment/issues/108.
=> Update Text Fragments URL (repo was renamed)

specs.json
See https://github.com/WICG/admin/issues/112.
=> Update Input Device Capabilities URL

src/find-specs.js
helps with assessing implementors interest
=> Link to Chrome status entry for found specs (if any)

specs.json
Developed by WebRTC WG and under development in Chrome
https://www.chromestatus.com/features/5713419084759040
=> Add MediaStream Depth to list of specs

specs.json, src/data/ignore.json
Marking storage partitioning as ignorable
=> Adding storage access and private click measurement as specs 

src/data/ignore.json
per https://github.com/w3c/browser-specs/issues/77#issuecomment-645276570
=> Ignore more specs

specs.json
complement MathML spec as other AAM spec complement other specs
=> Add MathML accessibility mappings

specs.json
Consistent with inclusion of webdriver2
=> Add Bidirectional Web Driver to list of specs

src/data/monitor-repos.json
WebAppSec SubOrigins (dormant)
input for workers & purification (no clear implementation plans)
=> Mark a few more specs as to be monitored

src/data/monitor-repos.json
Waiting on https://github.com/WICG/admin/issues/121
=> Mark kv-storage for monitoring

.github/workflows/report-new-specs.yml
per the syntax described in https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
=> Raise an issue for new specs only if the candidate list is not empty

src/find-specs.js
=> Make sure to detect TR versions of specs we're otherwise tracking

src/data/monitor.json
Addresses specs raised in https://github.com/w3c/browser-specs/issues/125
=> Add 2 CSS spec and WebXR Lighting spec to monitor list

src/data/monitor.json
=> Mark two new repos as not ready for inclusion

specs.json, src/data/ignore.json, src/data/monitor.json
Also ignore epub-revision (not for browsers), and monitor merchantbg (unclear future)
close #142
=> Add Screen Fold to spec, monitor Web Codecs

specs.json
Adopted by the Immersive Web WG, with already some early implementations
part of #145
=> Add WebXR Hand input to list of specs

src/data/monitor.json
=> Add WICG/raw-sockets to monitor list

specs.json, src/data/monitor.json
=> Add CSS Cascade 5

specs.json
See https://github.com/w3c/browser-specs/pull/174#issuecomment-707892910
=> Flag User Timing 2 as current specification

src/find-specs.js
formal change expected in the next few hours
=> Update Publishing Working Group to match its new name

src/data/monitor.json
=> Mark mediacapture insertable streams as to be monitored

specs.json, src/data/ignore.json, src/data/monitor.json
=> Reflect specs identified in December 7 spec finder

.github/workflows/lint.yml
There is apparently no way to access secrets from within an `if:` statement.
=> Fix test GitHub action

specs.json
Per https://github.com/w3c/csswg-drafts/issues/5804#issuecomment-747420357
Helps with https://github.com/w3c/webref/issues/77
=> Mark CSS Images 4 as a delta spec

src/data/monitor.json
=> Add UUID incubation to monitor list

specs.json, src/data/monitor.json
also add PFE to monitor list
close #239
=> Add two new stage 3 TC39 proposals 

src/data/ignore.json, src/data/monitor.json
=> Add WICG/app-history to monitor list, ignore gpuweb/types

.github/workflows/monitor-specs.yml, .github/workflows/report-new-specs.yml
=> Add Mike as reviewer of new and monitored specs

.github/candidate-specs.md
Needed in template too apparently?
=> Add Mike as reviewer

specs.json
2 new TC39 stage 3 proposals (error cause & temporal); device-posture is a derivative of already included screenfold; IndexDB3 is set to superseded IndexDb-2
fixes #260
=> Add newly identified specs

specs.json
Spec published under a new title and shortname:
https://www.w3.org/TR/device-posture/
=> Rename Screen Fold to Device Posture

specs.json
=> Add stage 3 TC39 proposal: class static init blocks

specs.json, src/data/monitor.json
Also add capability-delegation to monitor list
close #274
=> Update webcodecs URL

src/data/monitor.json
=> Mark Secure Payment Confirmation as to be monitored

specs.json
=> Reflect publication of WebAuthn Levle 3

specs.json, src/data/monitor.json
Move from monitor list - Document Policy shipped in Chromium 86 at least https://www.chromestatus.com/features/5744681033924608
=> Add Document Policy

specs.json
Both specs got published as First Public Working Draft.
=> Update URL of WebGPU, add WGSL

src/data/monitor.json
=> Add CHIPS WICG proposal to monitor list

specs.json
Closes https://github.com/w3c/browser-specs/issues/313
=> Add User Preference Media Features Client Hints Headers

specs.json
=> Add Web Neural Network API

specs.json
Spec just got published as First Public Working Draft.
=> Update URL of Web Neural Network API spec

src/data/monitor.json
=> Add preferCurrentTab to monitor list

.github/candidate-specs.md, .github/incorrect-base-url.md, .github/workflows/build.yml, .github/workflows/lint.yml, README.md, schema/data.json, schema/definitions.json, schema/index.json, schema/specs.json
Prepare migration to `main` as default branch.
=> Make "main" branch the default branch

src/check-base-url.js
=> Add exception to baseUrl check for httpwg.org URLs

src/data/monitor.json
=> Fix case in monitored repo name

README.md
close #331
Follow up to https://github.com/w3c/browser-specs/pull/325/commits/687e149c501167e2a189c28da28f648f80717fe6
=> Update documentation re repository.nightly availability

src/data/monitor.json
Both specs are marked as being proposals for now.
Fixed #346
=> Add Capture Handle and COEP: credentialless to monitor list

specs.json, src/compute-shortname.js, src/determine-filename.js, src/fetch-groups.js, test/index.js
=> Switch RFC URLs to rfc-editor.org

specs.json
Both proposals have entered stage 3 (even though the drafts have not yet been updated to reflect that change).
Raised in #350
=> Add TC39 findLast and Realms API proposals

specs.json, src/data/monitor.json
=> Add CSS Scoping Level 2, monitor Color API

specs.json
=> Fix `nightly.sourcePath` for `tracking-dnt`

specs.json
FPWD, with implementation in Chromium per https://www.chromestatus.com/feature/5680057076940800
close #369
=> Add VirtualKeyboard API

specs.json
Add Proposal : https://tc39.es/proposal-intl-locale-info
This fix's https://github.com/mdn/browser-compat-data/pull/12314
=> feat: add https://tc39.es/proposal-intl-locale-info

src/data/ignore.json
=> Ignore css-scoping2 as dup of cascade-6

src/data/monitor.json
=> Add PNG spec to monitor list

src/find-specs.js
=> Look for stage3 proposals for ECMA 402 too

src/find-specs.js
It hides legitimiate candidate updates
close #440
=> Make version check less loose

specs.json, src/data/monitor.json
This document contains some features that are implemented and shipped:
https://developer.mozilla.org/en-US/docs/Web/API/BeforeInstallPromptEvent#browser_compatibility
=> Add Manifest Incubations proposal

src/find-specs.js
now the case with WebSockets part of the html workstream
=> Handle situation where a WHATWG workstream has multiple standards

src/fetch-info.js
The server used to serve draft CSS specs sometimes returns the contents of the directory instead of the actual spec. The code happily considered that the content received in such cases was an actual spec and updated the spec title accordingly, e.g. to "Index of css-animations-2".
This update makes the code throw an error when this happens. This will make the job fail with an error even though there is nothing that we can really do about it, but that seems preferable to silently committing invalid titles to `index.json`.
=> Detect draft CSS specs server hiccups

specs.json, src/data/monitor.json
also Add WHATWG FS and WebSockets to monitor list (close #471)
=> Add WHATWG Test Utils to spec list 

specs.json
=> Add IFT RangeRequest

specs.json
for definitions extraction
close #483
=> Add I18N Glossary

specs.json
=> Remove mediacapture depth spec

specs.json
Requested in #488.
Four entries as this proposal is divided into four individual specs (all at stage 3).
=> Add TC39 Intl NumberFormat v3 proposal

src/data/ignore.json
=> Add CSS 2022 to ignore list

src/bump-packages-minor.js
@ is a reserved character in refering to a revision in the git CLI
=> Fix reference for minor bump script

specs.json
detected by find-specs once #450 is merged
=> Add WHATWG Web Sockets standard

specs.json
2 documents maintained in a single repo atm
```json
"added": [],
"updated": [
{
"url": "https://w3c.github.io/mediacapture-handle/actions/",
"shortname": "mediacapture-handle-actions",
"series": {
"shortname": "mediacapture-handle-actions",
"currentSpecification": "mediacapture-handle-actions",
"title": "The Capture-Handle Actions Mechanism",
"shortTitle": "The Capture-Handle Actions Mechanism",
"nightlyUrl": "https://w3c.github.io/mediacapture-handle/actions/"
},
"nightly": {
"url": "https://w3c.github.io/mediacapture-handle/actions/",
"sourcePath": "actions/index.html",
"repository": "https://github.com/w3c/mediacapture-handle",
},
"groups": [
{
"name": "Web Real-Time Communications Working Group",
"url": …
```
=> Add 2 new specs from WebRTC WG

specs.json
=> Add CSS Scroll Snap level 2

specs.json
=> Adding the EPUB 3.3 and EPUB 3.3. Reading Systems specification

src/data/monitor.json
=> Monitor new WebXR Capture spec

specs.json
See also https://github.com/w3c/csswg-drafts/issues/4766#issuecomment-585314599
=> Document change of nighlty shortname for CSS Viewport (née Device Adapt)

specs.json, src/data/monitor.json
This adds the Web App Launch Handler API (new name of `sw-launch`). Note the recent intent to ship in Chrome:
https://groups.google.com/a/chromium.org/g/blink-dev/c/hzR6LNu4JFk/m/ktN6KUEvBAAJ
This update also switches to the /TR URL for two CSS specs now published as First Public Working Drafts: Scroll-Linked Animations and CSS View Transitions.
This will fix #757 and add/update the following entries:
```json
{
"url": "https://wicg.github.io/web-app-launch/",
"shortname": "web-app-launch",
"series": {
"shortname": "web-app-launch",
"currentSpecification": "web-app-launch",
"title": "Web App Launch Handler API",
"shortTitle": "Web App Launch Handler API",
"nightlyUrl": "https://wicg.github.io/web-app-launch/"
},
"groups": [
{
"name": "Web …
```
=> Add Web App Launch Handler API, update 2 URLs after FPWD publication

specs.json, src/data/monitor.json
=> Add css-display-4

specs.json
=> Add ES Async Explicit Resource Management spec

src/data/monitor.json, src/find-specs.js
A couple of adjustments to address false positives reported in #955.
=> Handle false positives reported by find-specs

specs.json
Spec shortname and title got updated to `private-network-access` and "Private Network Access".
=> Update URL of Local network access proposal

specs.json
Also needed to fix build as the RDF Editor's Draft currently has a "WD" status.
=> Update URLs of rdf12-semantics and sparql12-entailment

specs.json, src/data/ignore.json
=> Add published specs from ex-Audiobooks WG to non-browser list

src/fetch-info.js
The Editor's Draft of the PNG spec currently has a "Working Draft" status.
=> Auto-convert "Working Draft" to "Editor's Draft" when needed

.github/workflows/build.yml, .github/workflows/check-base-url.yml, .github/workflows/lint.yml, .github/workflows/monitor-specs.yml, .github/workflows/release-package.yml, .github/workflows/report-new-specs.yml, .github/workflows/request-pr-review.yml
Needed to avoid deprecation notice about version of Node.js in job logs
=> Update versions of actions used in jobs

src/data/ignore.json
Spec is being integrated in HTML.
=> Add Close Watcher repo to ignore list

specs.json
Level 1 is about to be published as a Candidate Recommendation. Level 2 is a delta spec over Level 1.
Via #1044
=> Add CSS View Transitions Level 2

specs.json
Code cannot determine it automatically given that the file is at a nested level.
=> Add missing sourcePath for Managed Configuration proposal

src/data/monitor.json
=> Monitor WebRTC RTP Transport early proposal

src/fetch-info.js
Use of the `networkidle0` option does not work well with pages that maintain "stream" connections to some HTTP endpoint, as done in some CSS drafts. This update copies over and simplifies code from Reffy to ignore network requests to such stream resources (and also to avoid downloading images since we don't do anything with them).
Note I did not try to extract Reffy's code in the end, because it is a bit more embedded in Reffy's logic and, e.g., also handles multipage specs, which we're not interested in here.
=> Fix spec loading with Puppeteer

specs.json
The proposal will be added as "pending" (because it says it is an unofficial draft).
=> Add Web Smart Card API proposal

specs.json
Closes https://github.com/w3c/browser-specs/issues/1109.
=> Add WebP draft

specs.json, src/data/monitor.json
Shipping in Chrome
close #1144
=> Add Credentialless Iframe

.github/workflows/build.yml
Old version still used Node.js v12.
=> Bump version of push action

src/data/monitor.json
=> Monitor upcoming css-contain-4 spec

src/data/monitor.json
Only an explainer for now.
Via #1186.
=> Monitor Storage Access API extension to non-cookie storage

specs.json
FYI @msporny, this should help with https://github.com/w3c/vc-di-ecdsa/pull/57.
=> Add vc-data-integrity as a non-browser spec.

README.md
This PR attempts to clarify the purpose of the repository in the README.md based on comments by @dontcallmedom in PR https://github.com/w3c/browser-specs/pull/1205. /cc @jyasskin
=> Update repo purpose in README.md introduction.

specs.json
Fixes https://github.com/w3c/browser-specs/issues/1209.
=> Add ISO 14496-22  spec for Open Font Format

.github/candidate-specs.md, .github/workflows/monitor-specs.yml, .github/workflows/report-new-specs.yml
Hopefully reducing noise for him
=> Remove sideshowbarker from automatic assignees

.github/workflows/submit-suggested-spec.yml
=> Initialize git user in submission job

src/cli.js
=> Submission job: Fix title of created PR and link to issue

specs.json
Specs was published as a First Public Working Draft. Fixes #1331.
This should also move us closer to resuming builds...
=> Update URL of css-view-transitions-2

specs.json
=> Mark Custom State Pseudo class as obsoleted by Selectors 5

specs.json
based on reviewing https://github.com/tc39/proposals/blob/main/finished-proposals.md
=> Mark ES proposals merged in ES2024 as obsoleted

specs.json
=> Update URL of css-grid-3 following FPWD publication

specs.json
Spec was published as FPWD last week. Close #1555.
=> Update URL of Audio Session

specs.json
also document (unfortunate) former shortname
close #1580
=> Update GPC URL after FPWD

specs.json
=> Update element-timing URL

specs.json
Spec moved to the Web Machine Learning Community Group.
=> Update URL of writing-assistance-apis

specs.json
Via #1723. Lots of updates and issues raised against the spec in the past few days, and some parts are already shipping in Chrome.
=> Force standing of css-forms-1 to good

specs.json
Spec was published as FPWD. Close #1749
=> Update URL of ContentEditable spec

specs.json
Spec was published as FPWD. Close #1750
=> Update URL of css-forms-1

specs.json
Following migration to Privacy CG.
=> Update repository of CHIPS

specs.json
As discussed in #1812.
Close #1812.
(@dontcallmedom ,code does not yet support creating PRs that *update* a spec although that would certainly be great).
=> Move standing of Writing Assistance APIs to good

src/find-specs.js
The filtering steps were not applied in the right order and could report the same spec proposal more than once as a result, as some of the steps bypassed the ones that came after them. The logic now proceeds in a more logical manner and only skips further filtering steps when it discards the candidate.
=> Fix filtering steps in find-specs

specs.json
=> Update URL of css-mixins-1 following FPWD publication

specs.json
Following publication of FPWD. Close #2011.
=> Update URL of css-position-4

specs.json
This will replace the current ED entry with:
```json
{
"url": "https://www.w3.org/TR/css-borders-4/",
"shortname": "css-borders-4",
"series": {
"shortname": "css-borders",
"currentSpecification": "css-borders-4",
"title": "CSS Borders and Box Decorations Module",
"shortTitle": "CSS Borders and Box Decorations",
"releaseUrl": "https://www.w3.org/TR/css-borders/",
"nightlyUrl": "https://drafts.csswg.org/css-borders/"
},
"seriesVersion": "4",
"groups": [
{
"name": "Cascading Style Sheets (CSS) Working Group",
"url": "https://www.w3.org/Style/CSS/"
}
],
"release": {
"url": "https://www.w3.org/TR/css-borders-4/",
"status": "First Public Working Draft",
"filename": "Overview.html"
},
"nightly": {
"url": …
```
=> Update URL of css-borders-4 following publication of FPWD
